### PR TITLE
Fix: fixed Y & Y2 ticks misalignment (fixes #209)

### LINKED ISSUE #209: Y-Axis ticks misalignment
The tick marks for the second Y-Axis do not align with Axis lines. Both axis ticks should align with the axis lines, as to not create confusion. 

Problem: 
MicrosoftTeams-image (19)

Resolution:
Screen Shot 2020-04-28 at 4 15 58 PM

### PR DESCRIPTION
**Pull request by sdadn**
**What is the purpose of this pull request? (Check any that's applicable)**

-   [ ] Feature
-   [x] Bug fix
-   [ ] Dependency updates
-   [ ] Documentation updates
-   [ ] Build related changes
-   [ ] Changes an existing functionality
-   [ ] Other, please explain:

**Does this introduce a breaking change?**

-   [ ] Yes
-   [x] No

**What changes did you make? (Give an overview)**
Updated the logic behind displaying ticks. Previously, it was done automatically through the D3.js `nice` function, resulting in a different number of ticks, and hence misalignment. This was updated to be based on a fixed number for both Y & Y2 axis, and the values are calculated manually. The default number of ticks depends on the range of the Y & Y2 axis, but this can be overridden by passing a `ticksCount` property in the graph configuration object.

**Add any screenshots**
Before:
209_before

After:
209_after

### CODE REVIEW

**Comment by AshishMotanamGurunadham** [comment]
I guess we need to add ready for ux review label for this pr. Please correct me if i am wrong.

**Comment by sdadn** [comment]
> I guess we need to add ready for ux review label for this pr. Please correct me if i am wrong.

Yes, I believe you're right. But I don't seem to have permissions to update labels.

File: src/main/js/helpers/axis.js [hunk 1]
```diff
@@ -189,22 +190,38 @@ const getAxesScale = (axis, scale, config) => {
         scale.x,
         getAxisInfoOrientation(config.axis.x.orientation)
     );
+
+    if (
+        (config.ticksCount === undefined ||
```
Comment (Veera81) [inline src/main/js/helpers/axis.js:195]: Can you add a comment here that we are checking? What will happen if the consumer doesn't provide Y2 axis

File: src/main/js/helpers/axis.js [hunk 2]
```diff
@@ -249,6 +267,74 @@ const processTickValues = (ticks) => {
...
+ * Gets the number of ticks on the axis based on the upper and lower limits
+ *
+ * @private
+ * @param {number} range - range of values (upperLimit - lowerLimits)
+ * @returns {number} returns number of ticks for that range, based on a predefined set
+ */
+const getTicksCountFromRange = (range) => {
+    if (range <= constants.AXISRANGE_1) return constants.DEFAULT_TICKSCOUNT - 4;
+    if (range <= constants.AXISRANGE_2) return constants.DEFAULT_TICKSCOUNT - 3;
+    if (range <= constants.AXISRANGE_3) return constants.DEFAULT_TICKSCOUNT - 2;
```
Comment (Veera81) [inline src/main/js/helpers/axis.js:281]: Can we use the `switch` statement here?

File: src/main/js/helpers/axis.js [hunk 3]
```diff
@@ -249,6 +267,74 @@ const processTickValues = (ticks) => {
...
+    upperLimit,
+    ticksCount = constants.DEFAULT_TICKSCOUNT
+) => {
+    ticksCount = Math.abs(ticksCount);
+    const tickValues = [];
+    const [newLowerLimit, newUpperLimit] = d3
+        .scaleLinear()
+        .domain([lowerLimit, upperLimit])
+        .nice()
+        .domain();
```
Comment (Veera81) [inline src/main/js/helpers/axis.js:323]: What does this statement do? Can we add a comment here?

File: docs/core/Graph.md [hunk 4]
```diff
@@ -31,22 +31,23 @@ Graph is a set of graphs that share a common set of base visualization structure
...
+| showNoDataText   | boolean  | true                                          | Toggle to show no data text                                                                                                                                                             |
+| showShapes       | boolean  | true                                          | Toggle to show shapes in the line graph                                                                                                                                                 |
+| showVGrid        | boolean  | true                                          | Toggle to show vertical grid                                                                                                                                                            |
+| ticksCount       | number   | 3                                             | Number of ticks to show on the vertical axes, excluding the upper and lower limits, if not provided, the number of ticks will be calculated automatically depending on the Y & Y2 range |
```
Comment (Veera81) [inline docs/core/Graph.md:49]: Did we just add `ticksCount` property and alphabetized the properties?

File: docs/helpers/Ticks.md [hunk 5]
```diff
@@ -12,6 +13,12 @@ Ticks and Grid lines representing Axes values.
             -   [Datetime Buckets example](#datetime-buckets-example)
                 -   [Use Case](#use-case)
 
+## Overview
+
+Ticks are labels on the Axes to represent axis values. These values are determined by the upper and lower limits of its axis. If any datapoints on the graph exceed the upper or lower limits, the axis range will adjust accordingly and the tick labels will be updated.
+
+If there is only 1 axis in the graph, the tick intervals are calculated automatically using the d3.js `nice` function. If the Y2 axis is visible, the tick intervals are set based on the range of the Y & Y2 axes. This can be overridden to be custom using the `ticksCount` property in the graph configuration object. Acceptable values for `ticksCount` are `0 - 19`. Invalid values will result in `ticksCount` being ignored and going back to the default behavior.
```
Comment (Veera81) [inline docs/helpers/Ticks.md:20]: Did we have any dev examples?

**Comment by Veera81** [comment]
@sdadn LGTM analysis has given one alert for one change. Can you take a look at that alert?

https://lgtm.com/projects/g/cerner/carbon-graphs/rev/pr-91b8a7059028d447b4a25349f910ce7622b8dede

File: src/main/js/helpers/axis.js [hunk 6]
```diff
@@ -249,6 +267,74 @@ const processTickValues = (ticks) => {
...
+    if (range <= constants.AXISRANGE_1) return constants.DEFAULT_TICKSCOUNT - 4;
+    if (range <= constants.AXISRANGE_2) return constants.DEFAULT_TICKSCOUNT - 3;
+    if (range <= constants.AXISRANGE_3) return constants.DEFAULT_TICKSCOUNT - 2;
+    if (range <= constants.AXISRANGE_4) return constants.DEFAULT_TICKSCOUNT - 1;
+    return constants.DEFAULT_TICKSCOUNT;
+};
+
+/**
+ * Gets average number of ticks to be used based on the Y and Y2 axes
+ * * result from getTicksCountFromRange for Y and Y2 axes
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/axis.js:288]: Line 286?

File: docs/core/Graph.md (hunk 4 above)
Comment (sdadn) [reply docs/core/Graph.md:49]: Yes

File: package.json [hunk 7]
```diff
@@ -171,6 +171,9 @@
   "publishConfig": {
     "access": "public"
   },
+  "resolutions": {
+    "@babel/preset-env": "7.9.6"
+  },
```
[the remark this answers is not in the document]
Comment (sdadn) [reply package.json:176]: I was having trouble with some babel components not found after installing dependencies, similar to [this issue](https://stackoverflow.com/questions/60780664/could-not-find-plugin-proposal-numeric-separator).
Adding this change along with [this package](https://www.npmjs.com/package/npm-force-resolutions) was what helped fixed it. I included this change in the commit after needing to use the package again when I reinstalled all dependencies.

File: src/main/js/helpers/axis.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (AshishMotanamGurunadham) [reply src/main/js/helpers/axis.js:288]: line 288 i guess.

File: src/main/js/helpers/constants.js [hunk 8]
```diff
@@ -168,6 +168,12 @@ export default {
         top: -10,
         bottom: 20
     },
+    DEFAULT_TICKSCOUNT: 7,
+    TICKSCOUNT_MAXLIMIT: 19,
```
Comment (AshishMotanamGurunadham) [inline src/main/js/helpers/constants.js:172]: Any particular reason, why max limit is 19?

File: src/main/js/helpers/constants.js [hunk 9]
```diff
@@ -168,6 +168,12 @@ export default {
...
+    AXISRANGE_1: 20,
+    AXISRANGE_2: 50,
+    AXISRANGE_3: 100,
+    AXISRANGE_4: 500,
```
Comment (AshishMotanamGurunadham) [inline src/main/js/helpers/constants.js:176]: i guess it would be better to rename variables without numbers. Please correct me if i am wrong.

File: src/main/js/helpers/axis.js [hunk 10]
```diff
@@ -189,22 +190,38 @@ const getAxesScale = (axis, scale, config) => {
         scale.x,
         getAxisInfoOrientation(config.axis.x.orientation)
     );
+
+    if (
+        (config.ticksCount === undefined ||
+            config.ticksCount > constants.TICKSCOUNT_MAXLIMIT) &&
```
Comment (AshishMotanamGurunadham) [inline src/main/js/helpers/axis.js:196]: can we add about max tick limit in documentation.

File: src/main/js/helpers/constants.js (hunk 8 above)
Comment (sdadn) [reply src/main/js/helpers/constants.js:172]: 19 ticks would result in 20 divisions. The example graphs are 7-10 ticks. 20 seemed like a big enough number to accommodate as many ticks the consumer may need.

File: src/main/js/helpers/axis.js (hunk 10 above)
Comment (AshishMotanamGurunadham) [inline src/main/js/helpers/axis.js:196]: why are we calculating ticks if they exceed max limit, can't we just go with max limit? please correct me if i am wrong.

Comment (sdadn) [reply src/main/js/helpers/axis.js:196]: If you're talking about line 196, I'm checking to see if the consumer entered a value greater than `MAX_LIMIT`, e.g. 100 . If true, then the default number of ticks will be used.

File: src/main/js/helpers/constants.js (hunk 9 above)
Comment (sdadn) [reply src/main/js/helpers/constants.js:176]: If you have alternative suggestions, I'm open to them.

File: src/main/js/helpers/axis.js (hunk 10 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/helpers/axis.js:196]: in that case looks like they are expecting for large tick count right, why can't we go with max limit. why are we choosing to go with default value, any particular reason?

Comment (sdadn) [reply src/main/js/helpers/axis.js:196]: There's no technical difference between making tickCount the default or max value if given a value greater than max. This was just done so that `tickCount = undefined` and `tickCount > MAX_LIMIT` behavior will be consistent for simplicity.

File: src/main/js/helpers/axis.js (hunk 2 above)
Comment (sdadn) [reply src/main/js/helpers/axis.js]: [Fixed](https://github.com/cerner/carbon-graphs/pull/216/commits/62d2f2e7657e0d5ff36db3bbfb750a728bc22000)

File: src/main/js/helpers/constants.js (hunk 9 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/helpers/constants.js:176]: you can give something like AXISRANGE_TWENTY or AXISRANGE_ONE orsomething like that, my concern is just to get rid of those numbers.

File: src/main/js/helpers/axis.js (hunk 3 above)
Comment (sdadn) [reply src/main/js/helpers/axis.js:334]: This statement gets rounded off values for the upper and lower limits. I added a comment explaining it: [fix](https://github.com/cerner/carbon-graphs/pull/216/commits/6b0fcd338507d07f0d6d34bde63436eb3fb6d8a8)

File: src/main/js/helpers/axis.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/axis.js]: [Fixed](https://github.com/cerner/carbon-graphs/pull/216/commits/3dfd689bf78484fbcb5f3737344cb5a5d5048bc5)

[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/axis.js]: This was automatically done by the prettier.

File: src/main/js/helpers/axis.js [hunk 11]
```diff
@@ -189,22 +190,38 @@ const getAxesScale = (axis, scale, config) => {
...
+        hasY2Axis(config.axis)
+    )
+        config.ticksCount = getAverageTicksCount(
+            config.axis.y.domain.upperLimit - config.axis.y.domain.lowerLimit,
+            config.axis.y2.domain.upperLimit - config.axis.y2.domain.lowerLimit
+        );
+
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/axis.js:207]: [Added](https://github.com/cerner/carbon-graphs/pull/216/commits/0aa856892546b52db5cf458fea5cf8a8f333fd4a)

File: src/main/js/helpers/axis.js (hunk 1 above)
Comment (sdadn) [reply src/main/js/helpers/axis.js]: I added the comment [here](Added). If the consumer does not provide the Y2 axis, the Y axis ticks will be calculated automatically.

**Comment by sdadn** [comment]
> @sdadn LGTM analysis has given one alert for one change. Can you take a look at that alert?
> 
> https://lgtm.com/projects/g/cerner/carbon-graphs/rev/pr-91b8a7059028d447b4a25349f910ce7622b8dede

@Veera81 LGTM check is now passing.

File: src/main/js/helpers/axis.js (hunk 10 above)
Comment (sdadn) [reply src/main/js/helpers/axis.js:200]: Added [here](https://github.com/cerner/carbon-graphs/pull/216/commits/0aa856892546b52db5cf458fea5cf8a8f333fd4a). Is this what you mean?

File: src/main/js/helpers/constants.js (hunk 9 above)
Comment (sdadn) [reply src/main/js/helpers/constants.js]: [Fixed](https://github.com/cerner/carbon-graphs/pull/216/commits/d3818be6e4b65ca78df26f01f9cf674fbe9e3398). I'm avoiding having the value in the constant name so that the value can be easily updated without needing to rename the constant.

File: src/main/js/helpers/axis.js (hunk 10 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/helpers/axis.js:200]: I mean to add it in the ticks.md file.

Comment (sdadn) [reply src/main/js/helpers/axis.js:200]: It is [added](https://github.com/cerner/carbon-graphs/pull/216/commits/3a91cc57f6dcf9fdc6a4eb793e66e08fedac093b) in Ticks.md.

File: docs/helpers/Ticks.md (hunk 5 above)
Comment (sdadn) [reply docs/helpers/Ticks.md:20]: There is the Y2 axis sample that shows the the two axis now aligned.

File: src/main/js/helpers/axis.js (hunk 10 above)
Comment (sdadn) [reply src/main/js/helpers/axis.js:200]: It is [mentioned](https://github.com/cerner/carbon-graphs/pull/216/commits/3a91cc57f6dcf9fdc6a4eb793e66e08fedac093b) in the `ticks.md` file.

File: docs/helpers/Ticks.md (hunk 5 above)
Comment (sdadn) [reply docs/helpers/Ticks.md:20]: Also, we discussed offline that additional examples will be added after some prerequisite issues are resolved ( #84 )

File: package.json (hunk 7 above)
[the remark this answers is not in the document]
Comment (Veera81) [reply package.json:176]: I think we are having `@babel/preset-env` dependency in multiple times in the package.json.

If you remove these changes and pull the latest changes from master would fix the issue

File: src/main/js/helpers/axis.js [hunk 12]
```diff
@@ -249,10 +270,90 @@ const processTickValues = (ticks) => {
...
+    tickValues.push(newUpperLimit);
+
+    if (newLowerLimit < 0) tickValues.push(0);
+
+    const interval = (newUpperLimit - newLowerLimit) / (ticksCount + 1);
+
+    for (let index = 1; index <= ticksCount; index++)
+        tickValues.push(newLowerLimit + interval * index);
+
+    return tickValues;
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/axis.js:350]: No; order doesn't matter when passed to D3.js as the axis scale is set and it just puts the ticks in the appropriate position.

File: src/main/js/helpers/axis.js [hunk 13]
```diff
@@ -249,10 +270,90 @@ const processTickValues = (ticks) => {
...
+ *
+ * @private
+ * @param {number} range - range of values (upperLimit - lowerLimits)
+ * @returns {number} returns number of ticks for that range, based on a predefined set
+ */
+const getTicksCountFromRange = (range) => {
+    switch (true) {
+        case range <= constants.AXISRANGE_ONE:
+            return constants.DEFAULT_TICKSCOUNT - 4;
+
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/axis.js:285]: It'll be redundant as it'll be inaccessible after the return statement.

File: src/main/js/helpers/axis.js [hunk 14]
```diff
@@ -249,10 +270,90 @@ const processTickValues = (ticks) => {
...
+        case range <= constants.AXISRANGE_TWO:
+            return constants.DEFAULT_TICKSCOUNT - 3;
+
+        case range <= constants.AXISRANGE_THREE:
+            return constants.DEFAULT_TICKSCOUNT - 2;
+
+        case range <= constants.AXISRANGE_FOUR:
+            return constants.DEFAULT_TICKSCOUNT - 1;
+    }
+    return constants.DEFAULT_TICKSCOUNT;
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/axis.js:295]: We could do that; It just seemed weird to me to not have a final return outside the switch block. Will the `default` case cover all possible code paths?

File: src/main/js/helpers/axis.js (hunk 13 above)
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/axis.js:288]: [Fixed](https://github.com/cerner/carbon-graphs/pull/216/commits/a3ed74b6797c96eaef1c2db98d564885b43cb667)

File: src/main/js/helpers/axis.js [hunk 15]
```diff
@@ -249,10 +270,90 @@ const processTickValues = (ticks) => {
...
+    const [newLowerLimit, newUpperLimit] = d3
+        .scaleLinear()
+        .domain([lowerLimit, upperLimit])
+        .nice()
+        .domain();
+
+    tickValues.push(newLowerLimit);
+    tickValues.push(newUpperLimit);
+
+    if (newLowerLimit < 0) tickValues.push(0);
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/axis.js]: [Fixed](https://github.com/cerner/carbon-graphs/pull/216/commits/595a9105d3755f105db65c57b1f1003cb74f70af)

File: src/main/js/helpers/axis.js [hunk 16]
```diff
@@ -249,10 +270,90 @@ const processTickValues = (ticks) => {
...
+
+    const interval = (newUpperLimit - newLowerLimit) / (ticksCount + 1);
+
+    for (let index = 1; index <= ticksCount; index++)
+        tickValues.push(newLowerLimit + interval * index);
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/axis.js]: [Fixed](https://github.com/cerner/carbon-graphs/pull/216/commits/b7dd49a243674dbcff6216497de1c47b4fd55ed1)

File: src/main/js/helpers/axis.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/axis.js]: [removed](https://github.com/cerner/carbon-graphs/pull/216/commits/e54567d6dcdea162b2aca02ea69ce91923f3c522)

File: src/main/js/helpers/axis.js (hunk 10 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/helpers/axis.js:200]: i cannot see where you added max tick count in ticks.md file, can you please share the link of exact line.

**Comment by Veera81** [comment]
Can you fix the LGTM alert?

File: package.json (hunk 7 above)
[the remark this answers is not in the document]
Comment (sdadn) [reply package.json]: [Removed](https://github.com/cerner/carbon-graphs/pull/216/commits/b22f9be08cd1a92c1776720e584266ceaf686a93)
