### PR TITLE
Fix: Stacked bar goal line issue(fixes #304)

### LINKED ISSUE #304: Staked bar goal line Issue.
**What part of Carbon does this bug correlate to?**
General graph logic:

* [x]  Graph attributes (axes, legends, regions...etc.)
* [ ]  Other (please specify): 

Specific graph logic:

* [x]  Bar graph
* [ ]  Bubble graph
* [ ]  Gantt chart
* [ ]  Line graph
* [ ]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [ ]  Timeline

**Describe the bug**
- Goal lines in stacked bar graph is not loading onto graph as expected. 
https://engineering.cerner.com/carbon-graphs/#/regions/bar/stacked-goal-lines

**Screenshots**
**Current behavior**
image

**Expected behavior**
image

**Desktop (please complete the following information):**

-   OS: iOS
-   Browser: All browsers

### PR DESCRIPTION
**Pull request by AshishMotanamGurunadham**
Fixes: #304 

**What is the purpose of this pull request? (Check any that's applicable)**

-   [ ] Feature
-   [x] Bug fix
-   [ ] Dependency updates
-   [ ] Documentation updates
-   [ ] Build related changes
-   [ ] Changes an existing functionality
-   [ ] Other, please explain:

**Does this introduce a breaking change?**

-   [ ] Yes
-   [x] No

**What changes did you make? (Give an overview)**
- Made changes to logic which generate height for goal lines in stacked bar graph.

**Add any screenshots**
https://engineering.cerner.com/carbon-graphs/#/regions/bar/stacked-goal-lines
**Before**
image

**After**
image

### CODE REVIEW

File: src/main/js/controls/Line/Line.js [hunk 1]
```diff
@@ -190,7 +193,9 @@ class Line extends GraphContent {
                 ) {
                     graph.config.shouldHideAllRegion = false;
                 } else {
-                    graph.config.shouldHideAllRegion = !areRegionsIdentical(graph.svg);
+                    graph.config.shouldHideAllRegion = !areRegionsIdentical(
+                        graph.svg
+                    );
                 }
             } else {
                 graph.config.shouldHideAllRegion = true;
```
Comment (AshishMotanamGurunadham) [inline src/main/js/controls/Line/Line.js:201]: Please ignore this file since these are linter changes.

File: src/main/js/controls/PairedResult/PairedResult.js [hunk 2]
```diff
@@ -247,7 +246,6 @@ class PairedResult extends GraphContent {
                     utils.notEmpty(this.dataTarget.valueRegionSubset)
                 );
             } else {
-                
                 graph.config.shouldHideAllRegion = true;
             }
             if (graph.config.shouldHideAllRegion) {
```
Comment (AshishMotanamGurunadham) [inline src/main/js/controls/PairedResult/PairedResult.js:251]: Please ignore this file since these are linter changes.

File: src/main/js/controls/PairedResult/helpers/helpers.js [hunk 3]
```diff
@@ -625,7 +625,10 @@ const isSinglePairedResultTargetDisplayed = (config, graphContext) => {
...
     });
 
-    return isSingleTargetDisplayed(displayedPairedResults, graphContext.content);
+    return isSingleTargetDisplayed(
+        displayedPairedResults,
+        graphContext.content
+    );
 };
 /**
  * Checks the region data of Paired Result so that if one of regions for Paired Result data pairs are not provided,
```
Comment (AshishMotanamGurunadham) [inline src/main/js/controls/PairedResult/helpers/helpers.js:634]: Please ignore this file since these are linter changes.

**Review by jeremyfuksa — APPROVED** [review]

File: src/main/js/controls/Bar/helpers/goalLineHelpers.js [hunk 4]
```diff
@@ -182,7 +182,9 @@ const getYAxisRangePosition = (scale) => (bounds) =>
  * @returns {number} Height of the region for Y axes
  */
 const getRegionHeight = (regionPath, bounds, scale, config) => {
-    const upperBound = utils.getNumber(regionPath.attr(constants.Y_AXIS));
+    const upperBound = bounds.end
+        ? round2Decimals(scale[getRegionAxis(bounds)](bounds.end))
+        : 0;
```
Comment (Veera81) [inline src/main/js/controls/Bar/helpers/goalLineHelpers.js:187]: Why we are falling back to `0` if bounds.end value is not present?

Comment (Veera81) [reply src/main/js/controls/Bar/helpers/goalLineHelpers.js:187]: Is it supposed to be upperbound - lowerbound?

**Review by sdadn — APPROVED** [review]
