### PR TITLE
Fix: To not trigger popup for not truncated trackLabel (fixes #20)

### LINKED ISSUE #20: onClick triggers popup for Gantt Label items which are not truncated
**Describe the bug**
onClick triggers popup for Gantt Label items which are not truncated.

**To Reproduce**

1. Go to https://engineering.cerner.com/carbon-graphs/#/gantt/bar-types
2. Click on 'track label' for any gantt chart.
3. See error

**Expected behavior**
onClick should not trigger popup for Label which are not truncated. 
onClick should be triggered only for the truncated Label items. 

**Screenshots**
pop up for non truncated track label

### PR DESCRIPTION
**Pull request by pranav300**
**What is the purpose of this pull request? (Check any that's applicable)**

-   [ ] Feature
-   [x] Bug fix
-   [ ] Dependency updates
-   [ ] Documentation updates
-   [ ] Build related changes
-   [ ] Changes an existing functionality
-   [ ] Other, please explain:

**Does this introduce a breaking change?**

-   [ ] Yes
-   [x ] No

**What changes did you make? (Give an overview)**
Updated Gantt examples to have `onclick` only for `trackLabel` which are long enough to get truncated

**Add any screenshots**
Screenshot 2019-09-24 at 3 48 37 PM

### CODE REVIEW

**Comment by abhijit945** [comment]
There seems to be a misunderstanding here. 
The issue #20 is supposed to be for consumers, not the site per se. 
Currently track label click action is triggered regardless of whether they are truncated or otherwise. We would only want the `onClick` to be triggered when the label is truncated.

File: src/main/js/controls/Gantt/Track.js [hunk 1]
```diff
@@ -98,9 +99,14 @@ const addTrackLabelEventHandler = (canvasSVG, labelObj) =>
...
                 );
             }
-            d3.select(this).on("click", () => {
-                labelObj.onClick(labelObj.display, d3.select(this));
-            });
+            if (
+                labelObj.display.length >
+                constants.DEFAULT_LABEL_CHARACTER_LIMIT
+            ) {
+                d3.select(this).on("click", () => {
```
Comment (abhijit945) [inline src/main/js/controls/Gantt/Track.js]: The cursor pointer is [shown](https://github.com/cerner/carbon-graphs/blob/master/src/main/less/controls/Gantt.less#L6) only when the consumer provides `onClick` property via the `aria-disabled` attribute. So if you allow the code to pass through Ln 99 then it would show the cursor pointer but when you click nothing would show up. 

Ideally, it should be:

Truncated: 
image

Non-truncated: 
image

File: src/test/unit/controls/Gantt/Track-spec.js [hunk 2]
```diff
@@ -166,10 +166,7 @@ describe("Gantt -> Track", () => {
                     expect(labelPath.getAttribute("aria-disabled")).toBe(
                         "false"
                     );
-                    expect(onClickPrimaryFunctionSpy.calledOnce).toBeTruthy();
-                    expect(onClickPrimaryFunctionSpy.getCall(0).args[0]).toBe(
-                        smallLabel
-                    );
+                    expect(onClickPrimaryFunctionSpy.calledOnce).toBeFalsy();
```
Comment (abhijit945) [inline src/test/unit/controls/Gantt/Track-spec.js]: You can check for `aria-disabled` to be `true` here as well.

File: src/main/js/controls/Gantt/Track.js [hunk 3]
```diff
@@ -98,9 +99,14 @@ const addTrackLabelEventHandler = (canvasSVG, labelObj) =>
                     !utils.isFunction(labelObj.onClick)
                 );
             }
-            d3.select(this).on("click", () => {
-                labelObj.onClick(labelObj.display, d3.select(this));
-            });
+            if (
+                labelObj.display.length >
```
Comment (abhijit945) [inline src/main/js/controls/Gantt/Track.js]: There is a nifty helper for this `shouldTruncateLabel`

File: src/main/js/controls/Gantt/Track.js (hunk 1 above)
Comment (pranav300) [reply src/main/js/controls/Gantt/Track.js]: Fixed here https://github.com/cerner/carbon-graphs/pull/89/commits/869cb84d5e749a87f211ddc7135beec7d007283c.

File: src/test/unit/controls/Gantt/Track-spec.js (hunk 2 above)
Comment (pranav300) [reply src/test/unit/controls/Gantt/Track-spec.js]: Fixed here https://github.com/cerner/carbon-graphs/pull/89/commits/869cb84d5e749a87f211ddc7135beec7d007283c.

File: src/main/js/controls/Gantt/Track.js (hunk 3 above)
Comment (pranav300) [reply src/main/js/controls/Gantt/Track.js]: Fixed here https://github.com/cerner/carbon-graphs/pull/89/commits/869cb84d5e749a87f211ddc7135beec7d007283c.

**Comment by abhijit945** [comment]
The issue #20 is titled for Bar Graph's Axis Info Row but the description is for Gantt by mistake. Ill create a separate issue for Bar Graph.

**Comment by abhijit945** [comment]
Created https://github.com/cerner/carbon-graphs/issues/90 for Bar Graph Axis Info Row
