### PR TITLE
Fix: Fixed Selecting Paired Result Legend Item Affects Multiple Graphs (fixes #212)

### LINKED ISSUE #212: Paired Result Graph: Clicking legend of one graph affecting the graph another Graph
**Describe the bug**
Clicking the legend of one paired result in a graph affects another paired result present in the different graphs.
Looks like the issue is introduced in version 1.19.2. The previous version 1.19.1 is working fine.

**Link to CodeSandbox**

Use [this](https://codesandbox.io/s/autumn-dust-8vxc1?file=/src/data.js) template to reproduce the behavior. 

**Expected behavior**

**Screenshots**
Screenshot 2020-05-19 at 1 29 07 PM

**Desktop (please complete the following information):**

-   OS: iOS
-   Browser: chrome

**Additional context**
Looks like the issue is introduced in version [1.19.2](https://github.com/cerner/carbon-graphs/releases/tag/v1.19.2). The previous version [1.19.1](https://github.com/cerner/carbon-graphs/releases/tag/v1.19.1) is working fine.

### PR DESCRIPTION
**Pull request by JananiGunasekaran**
**What is the purpose of this pull request? (Check any that's applicable)**

-   [ ] Feature
-   [x] Bug fix
-   [ ] Dependency updates
-   [ ] Documentation updates
-   [ ] Build related changes
-   [ ] Changes an existing functionality
-   [ ] Other, please explain:

**Does this introduce a breaking change?**

-   [ ] Yes
-   [x] No

**What changes did you make? (Give an overview)**
Instead of selecting all .carbon-data-pair elements and passing them to showLine() method, select only those .carbon-data-pair elements that belong to the particular canvas for which a paired result legend item was clicked.

**Add any screenshots**

### CODE REVIEW

**Comment by JananiGunasekaran** [comment]
Since the travis CI - Pull Request was failing, I have run "npm update" command and committed the changes [here](https://github.com/JananiGunasekaran/carbon-graphs/commit/aef3bbd651786651640717ecb5c8791f33c71bf3). Both the checks for the PR passed now.

File: src/main/js/controls/PairedResult/helpers/helpers.js [hunk 1]
```diff
@@ -571,8 +571,15 @@ const clickHandler = (graphContext, control, config, canvasSVG) => (
...
-    showLine(config, boxPath);
+    const pairedBoxGroupClipPath = `url(#${config.clipPathId})`;
+    const pairedBoxGroup = d3.selectAll(`.${styles.pairedBoxGroup}`);
+    pairedBoxGroup.each(function () {
+        const clipPath = d3.select(this).attr("clip-path");
+        if (clipPath === pairedBoxGroupClipPath) {
+            const boxPath = d3.select(this).selectAll(`.${styles.pairedBox}`);
+            showLine(config, boxPath);
+        }
+    });
```
Comment (Veera81) [inline src/main/js/controls/PairedResult/helpers/helpers.js:582]: Can you add a comment here? Why we are doing this?

**Comment by Veera81** [comment]
Can you resolve the conflicts?

**Comment by JananiGunasekaran** [comment]
> Can you resolve the conflicts?

I have rebased with the latest master changes.

File: src/main/js/controls/PairedResult/helpers/helpers.js (hunk 1 above)
Comment (JananiGunasekaran) [reply src/main/js/controls/PairedResult/helpers/helpers.js:588]: Added comment [here](https://github.com/JananiGunasekaran/carbon-graphs/commit/a1db3e9718eb0fc6ca8551da9dc335a49a7d63de). 
The reason for this code change is that :
When there are multiple canvases with paired results in each canvas, selecting a paired result legend item in one canvas was affecting paired results in other canvases ( "the line connecting the high and low values were getting hidden/disappeared in other canvases as well") because earlier we were selecting all .carbon-data-pair elements ( including elements from all other canvases ) and passing them to showLine() method.

So now, we are going to select all .carbon-data-pairs-group elements and iterate through each selection. Here, we check the "clip-path" attribute for each selection and if the clip-path value matches the clip-path value of the particular canvas for which a paired result legend item was clicked, then select only those .carbon-data-pair elements and  pass them to showLine() method. 

This ensures that only that particular canvas's paired results line will be hidden when selecting a paired result legend item high/low.

**Comment by JananiGunasekaran** [comment]
> * Did we have any before and after UI changes for this?
> * Did we have any existing issue logged for this? or Would you mind creating the issue if the issue was not already there?
> * Do we have any dev examples for this change or documentation update?

1. Before this change, when there are multiple canvases with paired results in each canvas, and selecting a paired result legend item high:
image

After this change:
image

2. There is an existing issue logged for this. I have updated the PR title with the issue number. [This](https://github.com/cerner/carbon-graphs/issues/212) is the issue.

3. I have not added any dev examples for this particular change since it is a bug fix which was just affecting other canvases when selecting a paired result legend item of one canvas.
Since there is no change in the props, there was no change needed to be updated in the documentation.

Please let me know if anything else needs to be done.

File: src/test/unit/controls/PairedResult/PairedResultLoad-spec.js [hunk 2]
```diff
@@ -2007,5 +2007,34 @@ describe("Paired Result - Load", () => {
                     .getAttribute("aria-describedby")
             ).toEqual(pairPrimary.key);
         });
+        it("Does not affect paired results in other graphs", () => {
```
Comment (Veera81) [inline src/test/unit/controls/PairedResult/PairedResultLoad-spec.js:2010]: nit: we can add a describe block here.

```js
describe("when multiple canvas with paired results present", () => {
      it("shoud not affect paired results in other canvases", () => {
```

**Comment by Veera81** [comment]
@JananiGunasekaran Should we require UX Review for these changes? Or Are we ready for merge this PR?

File: src/test/unit/controls/PairedResult/PairedResultLoad-spec.js (hunk 2 above)
Comment (JananiGunasekaran) [reply src/test/unit/controls/PairedResult/PairedResultLoad-spec.js]: Added describe block [here](https://github.com/JananiGunasekaran/carbon-graphs/commit/9fd0a0d6ad845075c2a29d9795d0c699c78688fc).

**Comment by JananiGunasekaran** [comment]
> @JananiGunasekaran Should we require UX Review for these changes? Or Are we ready for merge this PR?

UX Review is not required for these changes. This was working previously. We are ready for merge.

**Comment by JananiGunasekaran** [comment]
@Veera81 After the last commit, LGTM analysis: JavaScript is failing. I couldn't find what the issue is from the logs. This is failing in my other fix graph padding PR as well after my last commit there.
