### PR TITLE
Fix: Fixed element.remove() issue with Internet Explorer(fixes #307)

### LINKED ISSUE #307: element.remove() function is not working in Internet explorer
**What part of Carbon does this bug correlate to?**
General graph logic:

* [x]  Graph attributes (axes, legends, regions...etc.)
* [ ]  Other (please specify): 

**Describe the bug**
- When we try to destroy one of the tooltip div element in Carbon-graphs, we are getting error like "**Object does not support property or method called remove**" because IE does not support **remove()** function for DOM elements.

**Expected behavior**
- div element should be removed during destroy without any errors in all browsers.

**Screenshots**
image

**Desktop (please complete the following information):**

-   Browser [internet explorer]

### PR DESCRIPTION
**Pull request by AshishMotanamGurunadham**
Fixes : #307 

**What is the purpose of this pull request? (Check any that's applicable)**

-   [ ] Feature
-   [x] Bug fix
-   [ ] Dependency updates
-   [ ] Documentation updates
-   [ ] Build related changes
-   [ ] Changes an existing functionality
-   [ ] Other, please explain:

**Does this introduce a breaking change?**

-   [ ] Yes
-   [x] No

**What changes did you make? (Give an overview)**
- Made changes to tooltip element remove method, so that it will also work in Internet explorer without any errors.

### CODE REVIEW

**Review by Veera81 — APPROVED** [review]

**Comment by mraplumb** [comment]
@AshishMotanamGurunadham are there any screenshots or evidence that you can provide of this working in IE and the other supported browsers since this was an issue with browser compatibility?

File: src/main/js/helpers/label.js [hunk 1]
```diff
@@ -338,7 +338,8 @@ const createTooltipDiv = () => {
  */
 const destroyTooltipDiv = () => {
     if (document.querySelector(`.${styles.labelPopupTooltip}`)) {
-        document.querySelector(`.${styles.labelPopupTooltip}`).remove();
+        const element = document.querySelector(`.${styles.labelPopupTooltip}`);
+        element.parentNode && element.parentNode.removeChild(element);
```
Comment (mraplumb) [inline src/main/js/helpers/label.js:342]: are we wanting to return `true` or possibly `false` from this?  If so, for what reason?

would it be more appropriate to use
```javascript
if(element.parentNode) {
   element.parentNode.removeChild(element);
}
```

**Comment by AshishMotanamGurunadham** [comment]
> @AshishMotanamGurunadham are there any screenshots or evidence that you can provide of this working in IE and the other supported browsers since this was an issue with browser compatibility?

**Outputs when graph is destroyed:** 

**Internet Explorer:**
image

**Google chrome:**
image

**Firefox:** 
image

**Safari:**
image

File: src/main/js/helpers/label.js (hunk 1 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/helpers/label.js:342]: It won't return any boolean value Andy. It will just remove the element present in DOM. 

**element.parentNode && element.parentNode.removeChild(element);**
It is like kind of if statement if node is present then it will execute the logic else No and it won't make any difference either way i guess Andy.

Comment (mraplumb) [reply src/main/js/helpers/label.js:342]: I think if we are attempting to validate that `element.parentNode` exists and then retrieve the child node, I would prefer to do that with an explicit if block

**Review by Veera81 — APPROVED** [review]

File: src/main/js/helpers/label.js (hunk 1 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/helpers/label.js]: Fixed [here](https://github.com/cerner/carbon-graphs/pull/309/files#diff-ee13bfd863a6dec0adb29b9fc41caf73R342).

**Review by mraplumb — APPROVED** [review]
