### PR TITLE
Fix: graph Axis Label Truncation(fixes #208)

### LINKED ISSUE #208: Line Graph Axis Label Truncation
A truncation pattern needs to be added for line graphs. Currently carbon will cut off an axis label if it is too long. When a label is too long, it should truncate and upon click reveal the entire label. The label when truncated should also include an '...' to indicate to user that there is more information that is not shown face up. 

This pattern should be consistent with what has been implemented for Gantt charts. (https://engineering.cerner.com/carbon-graphs/#/gantt/label-truncation) 

Screen Shot 2020-04-28 at 4 04 56 PM

### PR DESCRIPTION
**Pull request by AshishMotanamGurunadham**
**What is the purpose of this pull request? (Check any that's applicable)**

-   [ ] Feature
-   [x] Bug fix
-   [ ] Dependency updates
-   [ ] Documentation updates
-   [ ] Build related changes
-   [ ] Changes an existing functionality
-   [ ] Other, please explain:

**Does this introduce a breaking change?**

-   [ ] Yes
-   [x] No

**What changes did you make? (Give an overview)**

- In all axis, When a label is too long, it will truncate and upon click reveal the entire label. The label when truncated will include an '...' to indicate to user that there is more information that is not shown face up.

**Add any screenshots**

**Before**

image

**After**

image

image

image

image

**Added new tab called Label Truncation**

image

### CODE REVIEW

File: src/main/js/controls/Graph/helpers/helpers.js [hunk 1]
```diff
@@ -419,6 +452,45 @@ const createVGridHandler = (gridSVG, axis, style, config) => {
...
+            !canvasSVG.selectAll(`.${className} text`).text() ||
+            !utils.isFunction(axisObj.onClick)
+        ) {
+            return;
+        }
+        if (shouldTruncateLabel(axisObj.label, charLimit)) {
+            d3.select(this)
+                .style("cursor", "pointer")
+                .on("click", () => {
+                    axisObj.onClick(axisObj.label, d3.select(this));
```
Comment (Veera81) [inline src/main/js/controls/Graph/helpers/helpers.js:491]: Can you add a comment here why we are doing?

File: src/main/js/controls/Graph/helpers/helpers.js [hunk 2]
```diff
@@ -419,6 +452,45 @@ const createVGridHandler = (gridSVG, axis, style, config) => {
...
+ * @returns {object} d3 svg path
+ */
+const addLabelEventHandler = (canvasSVG, className, axisObj, charLimit) =>
+    canvasSVG.selectAll(`.${className} text`).each(function (displayVal) {
+        if (
+            !canvasSVG.selectAll(`.${className} text`).text() ||
+            !utils.isFunction(axisObj.onClick)
+        ) {
+            return;
+        }
```
Comment (Veera81) [inline src/main/js/controls/Graph/helpers/helpers.js:486]: here also can you add a comment?

File: src/main/js/helpers/axis.js [hunk 3]
```diff
@@ -997,20 +998,35 @@ const determineOutlierStretchFactor = (config) => {
...
+/**
+ * Checks if the Axis label needs to be truncated and returns the truncated value
+ *
+ * @private
+ * @param {string} label - Axis label display property
+ * @param {number} charLimit  - label character limit on axis
+ * @returns {string} if more than constants.DEFAULT_LABEL_CHARACTER_LIMIT then truncates,
+ * normal label otherwise
+ */
+const formatTrackLabel = (label, charLimit) =>
```
Comment (Veera81) [inline src/main/js/helpers/axis.js:1010]: Are we using this function for all graphs? Then should be updated to `formatLabel`?

File: src/main/js/controls/Graph/helpers/helpers.js [hunk 4]
```diff
@@ -419,6 +452,45 @@ const createVGridHandler = (gridSVG, axis, style, config) => {
...
 };
+/**
+ * calculates the character limit of label with respect to axis size
+ *
+ * @private
+ * @param {string} config - config object derived from input JSON
+ * @returns {object} character limit for both and y-axis
+ */
+const getAxesLabelCharacterLimits = (config) => ({
+    xAxisLimit: (3 * getXAxisWidth(config)) / 22,
```
[the remark this answers is not in the document]
Comment (Veera81) [reply src/main/js/controls/Graph/helpers/helpers.js:463]: Should we mention here which width requires how many characters?

File: src/test/unit/controls/Graph/GraphAxes-spec.js [hunk 5]
```diff
@@ -685,4 +693,205 @@ describe("Graph - Axes", () => {
...
+                    .textContent
+            ).toBe("Some Y2 Label");
+            done();
+        });
+    });
+    describe("Adds clickHandler for Label", () => {
+        const onClickPrimaryFunctionSpy = sinon.spy();
+        const onClickSecondaryFunctionSpy = sinon.spy();
+        const onClickThirdFunctionSpy = sinon.spy();
+        const onClickFourthFunctionSpy = sinon.spy();
```
Comment (Veera81) [inline src/test/unit/controls/Graph/GraphAxes-spec.js:812]: Can we move these constants to respective `it` block?

File: src/test/unit/controls/Graph/GraphAxes-spec.js [hunk 6]
```diff
@@ -685,4 +693,205 @@ describe("Graph - Axes", () => {
...
+                    .textContent
+            ).toBe("Some X Label");
+            expect(
+                fetchElementByClass(styles.axisLabelY2).querySelector("text")
+                    .textContent
+            ).toBe("Some Y2 Label");
+            done();
+        });
+    });
+    describe("Axes labels with different axes lengths", () => {
```
Comment (Veera81) [inline src/test/unit/controls/Graph/GraphAxes-spec.js:748]: axes widths?

File: src/test/unit/controls/Graph/GraphAxes-spec.js [hunk 7]
```diff
@@ -685,4 +693,205 @@ describe("Graph - Axes", () => {
...
+                fetchElementByClass(styles.axisLabelX).querySelector("text")
+                    .textContent
+            ).toBe("Some X Label");
+            expect(
+                fetchElementByClass(styles.axisLabelY2).querySelector("text")
+                    .textContent
+            ).toBe("Some Y2 Label");
+            done();
+        });
+    });
```
Comment (Veera81) [inline src/test/unit/controls/Graph/GraphAxes-spec.js:747]: Looks like these tests repeated below also? Can we remove these?

File: src/test/unit/controls/Graph/GraphAxes-spec.js [hunk 8]
```diff
@@ -685,4 +693,205 @@ describe("Graph - Axes", () => {
...
+            expect(
+                fetchElementByClass(styles.axisLabelY).querySelector("text")
+                    .textContent
+            ).toBe("Project long display value w...");
+            expect(
+                fetchElementByClass(styles.axisLabelY2).querySelector("text")
+                    .textContent
+            ).toBe("Project long display value w...");
+            done();
+        });
```
Comment (Veera81) [inline src/test/unit/controls/Graph/GraphAxes-spec.js:730]: Can we write the test cases like this for different widths 10, 25, 50, 100, 150, 200, 250 and 300?
```js
Describe("if axes width is 50", () -> {
          it("should not truncate the x-axis label", (done) =>{
          }

          it("should truncate the y-axis label", (done) =>{
          }

          it("should not truncate the y-2-axis label", (done) =>{
          }
}

Describe("if axes width is 100", () -> {
          it("should not truncate the x-axis label", (done) =>{
          }

          it("should truncate the y-axis label", (done) =>{
          }

          it("should not truncate the y-2-axis label", (done) =>{
          }
}
```

File: dev/examples/controls/gantt.js [hunk 9]
```diff
@@ -652,7 +652,7 @@ export const renderGanttStyle = (id) => {
         key: "track 7",
         trackLabel: {
             display: "Activity and Task",
-            onClick: loadTrackLabelPopup
```
[the remark this answers is not in the document]
Comment (AshishMotanamGurunadham) [reply dev/examples/controls/gantt.js:655]: No, since we are using same method for different labels in other graphs, i just renamed loadTrackLabelPopup to loadXAndYAxisLabelPopup.

File: dev/examples/data.js [hunk 10]
```diff
@@ -1721,6 +1726,51 @@ const DATA = [
...
+        LABEL_TRUNCATION: (id) => ({
+            bindTo: id,
+            bindLegendTo: null,
+            axis: {
+                x: {
+                    show: true,
+                    label: largeLabel,
+                    onClick: loadXAndYAxisLabelPopup,
+                    lowerLimit: 80,
+                    upperLimit: 280
```
[the remark this answers is not in the document]
Comment (AshishMotanamGurunadham) [reply dev/examples/data.js:1740]: Yes veera

File: src/main/js/controls/Graph/helpers/helpers.js [hunk 11]
```diff
@@ -419,6 +452,45 @@ const createVGridHandler = (gridSVG, axis, style, config) => {
         .classed(style, true)
         .call(translateVerticalGrid(axis, config));
 };
+/**
+ * calculates the character limit of label with respect to axis size
+ *
+ * @private
```
[the remark this answers is not in the document]
Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Graph/helpers/helpers.js:458]: This method is only in this class, so i did keep that method as private.

File: src/main/js/controls/Graph/helpers/helpers.js [hunk 12]
```diff
@@ -419,6 +452,45 @@ const createVGridHandler = (gridSVG, axis, style, config) => {
...
+ * @returns {object} character limit for both and y-axis
+ */
+const getAxesLabelCharacterLimits = (config) => ({
+    xAxisLimit: (3 * getXAxisWidth(config)) / 22,
+    yAndY2AxisLimit: config.height / 8
+});
+/**
+ * Adds onClick event for each tick.
+ * Criteria:
+ *  * Text needs to have a valid function for onClick
```
[the remark this answers is not in the document]
Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Graph/helpers/helpers.js:469]: it is like kind of sub point in criteria. That is the reason why. i added two stars in here.

File: src/main/js/controls/Graph/helpers/helpers.js [hunk 13]
```diff
@@ -419,6 +452,45 @@ const createVGridHandler = (gridSVG, axis, style, config) => {
...
+ *
+ * @private
```
[the remark this answers is not in the document]
Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Graph/helpers/helpers.js:472]: No it is only used in helpers file

File: dev/examples/data.js [hunk 14]
```diff
@@ -1721,6 +1726,51 @@ const DATA = [
...
+    },
+    {
+        LABEL_TRUNCATION: (id) => ({
+            bindTo: id,
+            bindLegendTo: null,
+            axis: {
+                x: {
+                    show: true,
+                    label: largeLabel,
+                    onClick: loadXAndYAxisLabelPopup,
```
Comment (mraplumb) [inline dev/examples/data.js:1738]: are we wanting to expose the onClick event allowing consumers to override the behavior?  If so, why would we want to do that?  I'm assuming it was modeled after the setup for Gantt but we need to decide if the behavior should be the same.

If kept, this property should probably be `labelOnClick`.  The current property name indicates that the `onClick` is for the axis when it is only for the label.  The documentation for Axes would also need to be updated to reflect the new optional property.
https://github.com/cerner/carbon-graphs/blob/master/docs/helpers/Axes.md

File: dev/examples/data.js (hunk 10 above)
[the remark this answers is not in the document]
Comment (mraplumb) [reply dev/examples/data.js:1740]: lowerLimit, upperLimit and label are all required properties
https://github.com/cerner/carbon-graphs/blob/master/docs/helpers/Axes.md

File: src/main/js/controls/Graph/helpers/helpers.js (hunk 2 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Graph/helpers/helpers.js:487]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/files#diff-608946a83d2c753fa2af8bbb05dc72d2R481)

File: src/main/js/controls/Graph/helpers/helpers.js (hunk 1 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Graph/helpers/helpers.js:493]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/files#diff-608946a83d2c753fa2af8bbb05dc72d2R488)

File: src/test/unit/controls/Graph/GraphAxes-spec.js (hunk 7 above)
Comment (AshishMotanamGurunadham) [reply src/test/unit/controls/Graph/GraphAxes-spec.js:748]: Actually we do need test that label do not truncate in that particular width and height. That is the reason why i repeated these in every case.

File: src/test/unit/controls/Graph/GraphAxes-spec.js (hunk 8 above)
Comment (AshishMotanamGurunadham) [reply src/test/unit/controls/Graph/GraphAxes-spec.js:731]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/files#diff-11aa0aaf6db553889f349765e88f7462R749)

File: src/test/unit/controls/Graph/GraphAxes-spec.js (hunk 5 above)
Comment (AshishMotanamGurunadham) [reply src/test/unit/controls/Graph/GraphAxes-spec.js]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/files#diff-11aa0aaf6db553889f349765e88f7462R1000)

File: dev/app.js [hunk 15]
```diff
@@ -218,6 +219,11 @@ renderSiteApp(
                     content: renderNoDataView,
                     title: "No Data"
                 },
+                {
+                    pathname: "/line/label-truncation",
+                    content: renderLineLabelTruncation,
+                    title: "Label Truncation"
+                },
```
[the remark this answers is not in the document]
Comment (AshishMotanamGurunadham) [reply dev/app.js:226]: fixed. Added image in the description.

File: src/main/js/controls/Graph/helpers/helpers.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Graph/helpers/helpers.js:469]: [Updated](https://github.com/cerner/carbon-graphs/commit/005b577ae3f43708560ca2241645bf3f370269be#diff-e136c9760b04608293a9d079cc909772R40) documentation.

Actually, For every ≈7 pixel(depends on character),  we can accommodate one uppercase character. As width of x-axis is long(around 1400px), if we assign 8px for each character we will get some small space left in x-axis. In order to fill that space i tried to assign  less than 8(22/3 i.e ≈7.33)px for each character in x-axis. That is the reason why i used different numbers to divide axis length for both x-axis and y-axis.

**Comment by SharathAlur** [comment]
@AshishMotanamGurunadham Is this going to fix https://github.com/cerner/carbon-graphs/issues/208 ?

**Comment by AshishMotanamGurunadham** [comment]
@SharathAlur yes it is going to fix issue number 208 and updated PR heading accordingly to let reviewers know the issue number.

**Comment by AshishMotanamGurunadham** [comment]
> A few follow up questions and observations:
> 
> * How are we handling this different for Gantt charts since the label is oriented horizontally instead of vertically and requires the 12 character limit?
> * The Line Graph group on the Demo site seems to be where we are putting all kinds of examples if they don't relate to one specific type of graph.  We should consider creating some sort of `General` group or groups related to Legends, Axes...etc. that impact multiple graph types.

In Gantt chart, label is generated in the place of tick. Whereas in line graph label is generated separately on the axis. That is the reason why label in line graph label is oriented vertically and gantt chart label is oriented horizontally. And based on the space they provided for the label 12 characters would be best to restrict in gantt chart.

File: docs/helpers/Axes.md [hunk 16]
```diff
@@ -37,6 +37,7 @@ Each axis - X, Y and Y2 should have the following properties:
 | ticks         | object   | null              | Refer [Ticks](Ticks.md)                                   |
 | rangeRounding | boolean  | true              | Toggle for range rounding                                 |
 | padDomain     | boolean  | true              | Toggle for disabling the padding (only for Y and Y2 axes) |
+| onLabelClick  | Function | undefined         | Any action that can be performed when clicking on label   |
```
Comment (sdadn) [inline docs/helpers/Axes.md:40]: Nit: since you're updating the documentation, can you alphabetize these fields?

File: src/main/js/controls/Graph/helpers/helpers.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (mraplumb) [reply src/main/js/controls/Graph/helpers/helpers.js:469]: if we are targeting 7.33 pixels per character, is there a reason that we cannot make it a little simpler and just go with 
```javascript
xAxisLimit: getXAxisWidth(config) / 7.333
```
It might be slightly less precise but it would be unlikely to affect the outcome.

File: docs/helpers/Axes.md (hunk 16 above)
Comment (AshishMotanamGurunadham) [reply docs/helpers/Axes.md]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/commits/f3cc18489de6df33f345b056dd0c815673f4c549#diff-e136c9760b04608293a9d079cc909772L35-R40)

File: src/main/js/controls/Graph/helpers/helpers.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Graph/helpers/helpers.js]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/commits/9a24873cfed7035a62bd84bc0a1eedf230f426d7#diff-608946a83d2c753fa2af8bbb05dc72d2R470). Changed pixels from fraction to decimal in xAxisLimit Calculation.

File: src/main/js/controls/Gantt/Track.js [hunk 17]
```diff
@@ -86,28 +85,21 @@ const addTrackLabelEventHandler = (canvasSVG, labelObj) =>
...
-                if (utils.isEmpty(d3.select(this).attr("aria-disabled"))) {
-                    d3.select(this).attr(
-                        "aria-disabled",
-                        !utils.isFunction(labelObj.onClick)
-                    );
-                }
-                d3.select(this).on("click", () => {
-                    labelObj.onClick(labelObj.display, d3.select(this));
-                });
+            if (!displayVal || !hasMatchingTrackLabel(this, labelObj.display)) {
```
Comment (Veera81) [inline src/main/js/controls/Gantt/Track.js:88]: - Can we add an in-line comment for this if condition? What we are checking?

- Did we miss to add a return statement when `if` condition satisfies?

File: src/main/js/controls/Gantt/Track.js [hunk 18]
```diff
@@ -86,28 +85,21 @@ const addTrackLabelEventHandler = (canvasSVG, labelObj) =>
...
+            } else {
+                shouldTruncateLabel(labelObj.display)
+                    ? d3
+                          .select(this)
+                          .style("cursor", "pointer")
+                          .on("click", () => {
+                              utils.isDefined(labelObj.onClick)
```
Comment (Veera81) [inline src/main/js/controls/Gantt/Track.js:95]: Probably, we can check this condition as well `utils.isFunction(labelObj.onClick)`

```js
utils.isDefined(labelObj.onClick) && utils.isFunction(labelObj.onClick)
```

Comment (Veera81) [inline src/main/js/controls/Gantt/Track.js:95]: Can you also add an inline comment here

// If the consumer provides onclick function, it will override default onClick functionality provided by Carbon-graphs

File: src/main/js/controls/Gantt/Track.js [hunk 19]
```diff
@@ -86,28 +85,21 @@ const addTrackLabelEventHandler = (canvasSVG, labelObj) =>
...
-                }
-                d3.select(this).on("click", () => {
-                    labelObj.onClick(labelObj.display, d3.select(this));
-                });
+            if (!displayVal || !hasMatchingTrackLabel(this, labelObj.display)) {
+            } else {
+                shouldTruncateLabel(labelObj.display)
+                    ? d3
+                          .select(this)
+                          .style("cursor", "pointer")
```
Comment (Veera81) [inline src/main/js/controls/Gantt/Track.js:93]: So we are cursor as a pointer as well?

File: src/main/js/controls/Graph/helpers/helpers.js [hunk 20]
```diff
@@ -419,20 +453,70 @@ const createVGridHandler = (gridSVG, axis, style, config) => {
...
+    charLimit,
+    axisType
+) =>
+    canvasSVG.selectAll(`.${className} text`).each(function (displayVal) {
+        shouldTruncateLabel(axisObj.label, charLimit)
+            ? d3
+                  .select(this)
+                  .style("cursor", "pointer")
+                  .on("click", () => {
+                      utils.isDefined(axisObj.onLabelClick)
```
Comment (Veera81) [inline src/main/js/controls/Graph/helpers/helpers.js:500]: Probably, we can check this condition as well `utils.isFunction(labelObj.onLabelClick)`

```js
utils.isDefined(labelObj.onLabelClick) && utils.isFunction(labelObj.onLabelClick)
```

Comment (Veera81) [reply src/main/js/controls/Graph/helpers/helpers.js:500]: What I have observed here, here axisObj has `onLabelClick` and Gantt chart has `onClick`. 

Both should have the same name?

File: src/test/unit/controls/Graph/GraphAxes-spec.js [hunk 21]
```diff
@@ -685,4 +695,473 @@ describe("Graph - Axes", () => {
...
+            triggerEvent(
+                fetchElementByClass(`${styles.axisLabelY2} text`),
+                "click",
+                () => {
+                    expect(onClickPrimaryFunctionSpy.calledOnce).toBeFalsy();
+                    done();
+                }
+            );
+        });
+        it("Click functionality disabled when, small label and onLabelClick function is provided", (done) => {
```
Comment (Veera81) [inline src/test/unit/controls/Graph/GraphAxes-spec.js:1028]: Did we cover the scenario?

- If the small label is provided and `onLabelClick` function is **not** provided

Comment (Veera81) [inline src/test/unit/controls/Graph/GraphAxes-spec.js:1028]: nit: We can write like below for all event handler test cases

**E.g**..

```js
describe("when small label and onLabelClick function is provided", (done) => {
      it("should disable onLabelClick functionality", (done) =>
         ......................
      } 
}

describe("when small label is provided and onLabelClick function is not provided", (done) => {
      it("should disable onLabelClick functionality", (done) =>
         ......................
      } 
}

describe("when large label and onLabelClick function is provided", (done) => {
      it("should enable onLabelClick functionality", (done) =>
         ......................
      } 
}

describe("when large label is provided and onLabelClick function is not provided", (done) => {
      it("should enable onLabelClick functionality", (done) =>
         ......................
      } 
}
```

File: src/main/js/helpers/label.js [hunk 22]
```diff
@@ -50,6 +50,64 @@ const truncateLabel = (
...
+        .append("div", "#tooltip")
+        .attr("id", "overlay")
+        .classed("overlay", true)
+        .on("click", clickHandler);
+    // Position popup
+    return axisType === "y2"
+        ? d3
+              .select("#tooltip")
+              .style("left", `${d3.event.pageX - 250}px`)
+              .style("top", `${d3.event.pageY + 5}px`)
```
Comment (Veera81) [inline src/main/js/helpers/label.js:105]: Can you add an inline comment here why we are doing differently for the y-2 axis?

File: src/test/unit/controls/Gantt/Track-spec.js [hunk 23]
```diff
@@ -190,6 +190,32 @@ describe("Gantt -> Track", () => {
                 }
             );
         });
+        it("Executes callback when, clicked on truncated label and onClick function is not provided", (done) => {
```
Comment (Veera81) [inline src/test/unit/controls/Gantt/Track-spec.js:193]: nit: Can we write like below for all event handler test cases

**E.g**..

```js
describe("when small label and onLabelClick function is provided", (done) => {
      it("should disable onLabelClick functionality", (done) =>
         ......................
      } 
}

describe("when small label is provided and onLabelClick function is not provided", (done) => {
      it("should disable onLabelClick functionality", (done) =>
         ......................
      } 
}

describe("when large label and onLabelClick function is provided", (done) => {
      it("should enable onLabelClick functionality", (done) =>
         ......................
      } 
}

describe("when large label is provided and onLabelClick function is not provided", (done) => {
      it("should enable onLabelClick functionality", (done) =>
         ......................
      } 
}
```

File: src/main/js/controls/Gantt/Track.js (hunk 17 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Gantt/Track.js:89]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/commits/3d75d6b1109fb3da7bad04f51b1228bd6bcaaf93#diff-bdf6ac5b711158c299d4a3c2dce8913fR88). Added inline comments for if condition.

Even I first added return statement but linter want me to remove return which will also do same thing(return undefined).

File: src/main/js/controls/Gantt/Track.js (hunk 18 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Gantt/Track.js]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/commits/3d75d6b1109fb3da7bad04f51b1228bd6bcaaf93#diff-bdf6ac5b711158c299d4a3c2dce8913fR97)

Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Gantt/Track.js]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/commits/3d75d6b1109fb3da7bad04f51b1228bd6bcaaf93#diff-bdf6ac5b711158c299d4a3c2dce8913fR96)

File: src/main/js/controls/Graph/helpers/helpers.js (hunk 20 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Graph/helpers/helpers.js]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/commits/3d75d6b1109fb3da7bad04f51b1228bd6bcaaf93#diff-608946a83d2c753fa2af8bbb05dc72d2R500) Added function check for the labelObj.onLabelClick.

The reason why we have different name is, gantt chart has separate object for label. In that case we can just have onClick which can clearly states that  onClick is for label but in graphs we do not have separate object for label that is the reason why we named onLabelClick.

File: src/test/unit/controls/Graph/GraphAxes-spec.js (hunk 21 above)
Comment (AshishMotanamGurunadham) [reply src/test/unit/controls/Graph/GraphAxes-spec.js]: @Veera81 that case got covered already. please take a look at this [code](https://github.com/cerner/carbon-graphs/pull/242/commits/3d75d6b1109fb3da7bad04f51b1228bd6bcaaf93#diff-7fb4a16b40433875e7e73811189b4f84R164-R178) .

Comment (AshishMotanamGurunadham) [reply src/test/unit/controls/Graph/GraphAxes-spec.js]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/commits/3d75d6b1109fb3da7bad04f51b1228bd6bcaaf93#diff-7fb4a16b40433875e7e73811189b4f84R164)

File: src/main/js/helpers/label.js (hunk 22 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/helpers/label.js]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/commits/3d75d6b1109fb3da7bad04f51b1228bd6bcaaf93#diff-ee13bfd863a6dec0adb29b9fc41caf73R102)

File: src/test/unit/controls/Gantt/Track-spec.js (hunk 23 above)
Comment (AshishMotanamGurunadham) [reply src/test/unit/controls/Gantt/Track-spec.js]: [fixed](https://github.com/cerner/carbon-graphs/pull/242/commits/3d75d6b1109fb3da7bad04f51b1228bd6bcaaf93#diff-7fb4a16b40433875e7e73811189b4f84R164)

**Comment by Veera81** [comment]
@AshishMotanamGurunadham Are we ready to merge the PR?

**Comment by AshishMotanamGurunadham** [comment]
@Veera81 There are three approvals we can merge it.

**Comment by Veera81** [comment]
@sdadn Can you review and approve the PR? So that we can merge this PR?
