### PR TITLE
Fix: Y2 axis going out of scope when hasCustomPadding is true.

### LINKED ISSUE #110: Y2 label getting truncated when hasCustomPadding is true.
**Describe the bug**
 Y2-axis label is getting truncated when `hasCustomPadding`
 is true.

**To Reproduce**

1. Go to the code and add custom padding to [this](https://github.com/cerner/carbon-graphs/blob/master/dev/examples/controls/line.js#L34) similar to that in constants.
3. run the local server
4. Go to this link http://localhost:9991/#/line/y2-axis

**Expected behavior**
Y2-axis label should be visible with hasCustomProperty.

**Screenshots**
Screenshot 2019-11-12 at 3 27 31 PM

**Desktop (please complete the following information):**

-   OS: IOS
-   Browser: Chrome

### PR DESCRIPTION
**Pull request by pranav300**
**What is the purpose of this pull request? (Check any that's applicable)**

-   [ ] Feature
-   [x] Bug fix
-   [ ] Dependency updates
-   [ ] Documentation updates
-   [ ] Build related changes
-   [ ] Changes an existing functionality
-   [ ] Other, please explain:

**Does this introduce a breaking change?**

-   [ ] Yes
-   [x] No

**What changes did you make? (Give an overview)**
Fixes #110 #81

While working on issue #110, I found that PR #107 introduced a bug in the graph construct. As there was slight clipping of the y-axis and y2-axis at the top. Due to the change in padding-bottom in constants. So, I am fixing that as well in this PR.

**Add any screenshots**
Y2 graph in DevSite.
image

### CODE REVIEW

File: src/main/js/controls/Timeline/helpers/creationHelpers.js [hunk 1]
```diff
@@ -91,7 +91,7 @@ const getXAxisXPosition = (config) => config.padding.left;
  * @returns {number} Position for the axis
  */
 const getXAxisYPosition = (config) =>
-    (config.padding.top + config.padding.bottom) * 2;
+    config.padding.top * 1.5 + config.padding.bottom;
```
Comment (abhijit945) [inline src/main/js/controls/Timeline/helpers/creationHelpers.js]: Why are we doing this? Didnt we fix a bug for firefox recently that increased the padding top? 
My concern is that, the unit tests no longer give us the protection in this case. 
Unit tests have a number 300. Fix 1 increases top to 20 -> Unit test now checks for 320.
Fix 2 decreases top by half -> Unit test now checks for 160. i.e. this no longer tests the Fix 1

Comment (pranav300) [reply src/main/js/controls/Timeline/helpers/creationHelpers.js]: > Why are we doing this? Didn't we fix a bug for firefox recently that increased the padding-top?

IN PR #107, we had decreased the padding-bottom from `5` to `2.5`. Which made it work for timeline but as a result, all the graphs created from graph-construct had their top Y and Y2 axis ticks getting clipped. So, I have reverted the padding-bottom back to `5` and to solve the timeline issue this change `config.padding.top * 1.5 + config.padding.bottom;` was made. As this would only affect the timeline. 
What do you think? @abhijit945

Comment (abhijit945) [reply src/main/js/controls/Timeline/helpers/creationHelpers.js]: I am good with that as long as we are only changing the unit tests for impacted functionality.

**Comment by abhijit945** [comment]
Please update the commit message to a single commit with appropriate commit message.

**Comment by abhijit945** [comment]
@pranav300 This has my +1, you can get another reviewer to get review it and potentially merge it 👍

File: src/main/js/helpers/constants.js [hunk 2]
```diff
@@ -149,7 +149,7 @@ export const AXES_ORIENTATION = {
 export default {
     PADDING: {
         top: 10,
-        bottom: 2.5,
+        bottom: 5,
```
Comment (abhijit945) [inline src/main/js/helpers/constants.js]: Does doing this fix the issue happening in the site right now (_The topmost values in the Y Axis are cut-off_)? 

image

Comment (pranav300) [reply src/main/js/helpers/constants.js]: Yes, it fixes it.
