### PR TITLE
Fix: Fixed graphs to not render data points where y value is null.

### LINKED ISSUE #161: Toggling of Non-Contiguous Line Legend Adds a Data Point
When the legend item is toggled off and then on again for a non-contiguous line, a random point will appear at the bottom of the graph. 

When the legend item is toggled back on, no new points should be added to the graph 

Screen Shot 2020-02-04 at 11 44 34 AM

### PR DESCRIPTION
**Pull request by pranav300**
**What is the purpose of this pull request? (Check any that's applicable)**

-   [ ] Feature
-   [X] Bug fix
-   [ ] Dependency updates
-   [ ] Documentation updates
-   [ ] Build related changes
-   [ ] Changes an existing functionality
-   [ ] Other, please explain:

**Does this introduce a breaking change?**

-   [ ] Yes
-   [X] No

**What changes did you make? (Give an overview)**
I have put conditions in `Gantt, Timeline, Line, Scatter` so that dataPoints are not rendered when dataPoint y value is null and removed function `shouldHideDataPoints`, as it seemed unrequired. Because on the first load all the data is shown. And the hiding and visibility of the dataPoints are later taken care of by clickHandler update in [this PR](https://github.com/cerner/carbon-graphs/pull/140).

closes #161

### CODE REVIEW

File: src/main/js/controls/Gantt/helpers/actionHelpers.js [hunk 1]
```diff
@@ -276,8 +262,24 @@ const drawActionDataPoints = (scale, config, canvasSVG) =>
         .classed(styles.pointGroup, true)
         .each(function(dataPoint, index) {
             const dataPointSVG = d3.select(this);
-            renderSelectionPath(scale, config, dataPointSVG, dataPoint, index);
-            renderDataPointPath(scale, config, dataPointSVG, dataPoint, index);
+            if (dataPoint.y !== null) {
```
Comment (abhijit945) [inline src/main/js/controls/Gantt/helpers/actionHelpers.js]: There is nothing wrong with this approach but we could make use of `d3.select.filter` function instead?
It would work this way:
```js
d3.select("body")
    .selectAll("p")
    .data(
        [4, 8, 15, 16, 23, 42].filter(function(d) {
            return d < 10;
        })
    )
    .enter()
    .append("div")
    .text(function(d) {
        return d;
    });
```

Comment (pranav300) [reply src/main/js/controls/Gantt/helpers/actionHelpers.js]: done here https://github.com/cerner/carbon-graphs/pull/164/commits/b4d0cd4a3fe85882be8c7acfd2c8cde97ca5dda0.

File: src/test/unit/controls/Scatter/ScatterLoad-spec.js [hunk 2]
```diff
@@ -511,10 +509,10 @@ describe("Scatter - Load", () => {
                     );
                     expect(scatterGroup.length).toBe(1);
                     expect(
-                        scatterGraphContainer
-                            .querySelectorAll(`.${styles.point}`)[2]
-                            .getAttribute("aria-hidden")
-                    ).toBe("true");
+                        scatterGraphContainer.querySelectorAll(
+                            `.${styles.point}`
```
Comment (abhijit945) [inline src/test/unit/controls/Scatter/ScatterLoad-spec.js]: Why is this impacting current tests?

File: src/main/js/controls/Scatter/helpers/helpers.js [hunk 3]
```diff
@@ -182,7 +182,7 @@ const draw = (scale, config, canvasSVG, dataTarget) => {
     const pointPath = scatterSVG
         .select(`.${styles.currentPointsGroup}`)
         .selectAll(`.${styles.point}`)
-        .data(getDataPointValues);
+        .data(getDataPointValues(dataTarget).filter((d) => d.y != null));
```
Comment (abhijit945) [inline src/main/js/controls/Scatter/helpers/helpers.js]: `!==`

File: src/test/unit/controls/Scatter/ScatterLoad-spec.js (hunk 2 above)
Comment (pranav300) [reply src/test/unit/controls/Scatter/ScatterLoad-spec.js]: The current tests were checking whether a point exists in the DOM whose y value is null and having `aria-hidden` to be `true`. But after the changes that point is not present in the DOM itself, So the tests were failing. 
In the tests now, it is checking the total no. of `carbon-data-points` present in the DOM. Which is then compared with the length of dataArray after subtracting the no of data points with y value null.

File: src/main/js/controls/Scatter/helpers/helpers.js (hunk 3 above)
Comment (pranav300) [reply src/main/js/controls/Scatter/helpers/helpers.js]: done here https://github.com/cerner/carbon-graphs/pull/164/commits/2ea11e54b41f833eab9355a6016affc125191f3d.

Comment (pranav300) [reply src/main/js/controls/Scatter/helpers/helpers.js]: done here https://github.com/cerner/carbon-graphs/pull/164/commits/2ea11e54b41f833eab9355a6016affc125191f3d.

**Comment by abhijit945** [comment]
Dont forget to add `fixes (#161)` to your PR, that way GitHub closes the issue when this PR is closed.
