### PR TITLE
Fix: Axis label moving when space is passed as label(fixes #298)

### LINKED ISSUE #298: Axis label moving when space is passed as label
**Describe the bug**
When the consumer passes in a space as the axis label, the symbols shift and move over the axis range. 

**Expected behavior**
The symbols should not move when a space is passed in as an axis label.

**Screenshots**
When a spaced is passed as label:
image

When a '--' is passed as label: 
image

### PR DESCRIPTION
**Pull request by AshishMotanamGurunadham**
Fixes : #298 

**What is the purpose of this pull request? (Check any that's applicable)**

-   [ ] Feature
-   [x] Bug fix
-   [ ] Dependency updates
-   [ ] Documentation updates
-   [ ] Build related changes
-   [ ] Changes an existing functionality
-   [ ] Other, please explain:

**Does this introduce a breaking change?**

-   [ ] Yes
-   [x] No

**What changes did you make? (Give an overview)**
- Fixed y-axis shape and y-axis overlapping issue when y2-axis is true.
- Removed white shape box on the page which appears during resize.

**Add any screenshots**

**Axis label moving when space is passed as label**
https://engineering.cerner.com/carbon-graphs/#/line/simple
**Before**
image

**After**
image

**Removing white shaped box in the page during resize**
https://engineering.cerner.com/carbon-graphs/#/line/simple
**Before**
image

**After**
image

### CODE REVIEW

**Comment by AshishMotanamGurunadham** [comment]
@jeremyfuksa You can just pull the brach and see the output as you did before.  And second issue can be seen on resize.

**Review by jeremyfuksa — APPROVED** [review]

File: src/main/js/controls/Line/Line.js [hunk 1]
```diff
@@ -190,7 +193,9 @@ class Line extends GraphContent {
                 ) {
                     graph.config.shouldHideAllRegion = false;
                 } else {
-                    graph.config.shouldHideAllRegion = !areRegionsIdentical(graph.svg);
+                    graph.config.shouldHideAllRegion = !areRegionsIdentical(
+                        graph.svg
+                    );
                 }
             } else {
                 graph.config.shouldHideAllRegion = true;
```
Comment (AshishMotanamGurunadham) [inline src/main/js/controls/Line/Line.js:201]: Please ignore this file since these are linter changes.

File: src/main/js/controls/PairedResult/PairedResult.js [hunk 2]
```diff
@@ -247,7 +246,6 @@ class PairedResult extends GraphContent {
                     utils.notEmpty(this.dataTarget.valueRegionSubset)
                 );
             } else {
-                
                 graph.config.shouldHideAllRegion = true;
             }
             if (graph.config.shouldHideAllRegion) {
```
Comment (AshishMotanamGurunadham) [inline src/main/js/controls/PairedResult/PairedResult.js:251]: Please ignore this file since these are linter changes

File: src/main/js/controls/PairedResult/helpers/helpers.js [hunk 3]
```diff
@@ -625,7 +625,10 @@ const isSinglePairedResultTargetDisplayed = (config, graphContext) => {
...
     });
 
-    return isSingleTargetDisplayed(displayedPairedResults, graphContext.content);
+    return isSingleTargetDisplayed(
+        displayedPairedResults,
+        graphContext.content
+    );
 };
 /**
  * Checks the region data of Paired Result so that if one of regions for Paired Result data pairs are not provided,
```
Comment (AshishMotanamGurunadham) [inline src/main/js/controls/PairedResult/helpers/helpers.js:634]: Please ignore this file since these are linter changes

File: src/main/js/helpers/label.js [hunk 4]
```diff
@@ -329,6 +329,7 @@ const createTooltipDiv = () => {
     d3.select("body")
         .append("div")
         .attr("id", styles.labelPopupTooltip)
+        .style("display", "none")
```
Comment (Veera81) [inline src/main/js/helpers/label.js:332]: Is it a passive change?

Comment (AshishMotanamGurunadham) [reply src/main/js/helpers/label.js:332]: No Veera, it will only fix the white box around graph issue. It won't effect anything other than that.

**Review by Veera81 — APPROVED** [review]

**Review by sdadn — APPROVED** [review]
