### PR TITLE
Fix: updated styling to fix popup issue(fixes #271, #6)

### LINKED ISSUE #271: Popup is not opening for the truncated Label
**Describe the bug**
Popup is not opening for the truncated label after consuming in the project. The mouse pointer changes as expected but tooltip is not being displayed on click.

**Link to CodeSandbox**
Use [this](https://codesandbox.io/s/festive-chandrasekhar-un8dx) template to reproduce the behavior. 

**Expected behavior**
The mouse cursor should change to pointer (it is working now) and on click, a default popup should open displaying the complete label string.

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS] NA
-   Browser [e.g. chrome, safari] NA

**Additional context**
Linked issue: https://github.com/cerner/carbon-graphs/issues/208

After a bit of investigation, I found the issue is not reproducible in the [demo site](https://engineering.cerner.com/carbon-graphs/#/line/label-truncation) because, the demo site has a html tag with class tooltip. The main js code is actually using the tooltip present in the demo site to show/hide the popup.

### PR DESCRIPTION
**Pull request by AshishMotanamGurunadham**
**What is the purpose of this pull request? (Check any that's applicable)**

-   [ ] Feature
-   [x] Bug fix
-   [ ] Dependency updates
-   [ ] Documentation updates
-   [ ] Build related changes
-   [ ] Changes an existing functionality
-   [ ] Other, please explain:

**Does this introduce a breaking change?**

-   [ ] Yes
-   [x] No

**What changes did you make? (Give an overview)**
-  Previously consumer cannot see the default popup provided by Carbon-graph. Due to this code changes bug will get fixed and now consumer can see the default popup provided by Carbon-graphs.

### CODE REVIEW

File: src/main/js/helpers/label.js [hunk 1]
```diff
@@ -292,6 +295,25 @@ const translateLabelShapeContainer = (config, shapeContainerPath) => {
...
+        .classed(styles.labelPopupTooltip, true);
+};
+
+/**
+ * Removes popup tooltip div element
+ */
+const destroyTooltipDiv = () => {
+    if (document.querySelector(`.${styles.labelPopupTooltip}`)) {
+        document.querySelector(`.${styles.labelPopupTooltip}`).remove();
+    }
```
Comment (Veera81) [inline src/main/js/helpers/label.js:314]: Do we need to remove `${styles.labelPopupOverlay}` also here?

File: src/main/js/controls/Graph/Graph.js [hunk 2]
```diff
@@ -393,6 +396,7 @@ class Graph extends Construct {
      * @returns {Graph} - Graph instance
      */
     destroy() {
+        destroyTooltipDiv();
```
Comment (Veera81) [inline src/main/js/controls/Graph/Graph.js:399]: Can we use the `d3RemoveElement` function for this? instead of a newly created function?

File: src/main/js/helpers/label.js (hunk 1 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/helpers/label.js:314]: not necessary i guess veera because we are creating and removing it in same place if necessary.

File: src/main/js/controls/Graph/Graph.js (hunk 2 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Graph/Graph.js:399]: I tried doing that, Since we are creating div element outside of container d3RemoveElement will not work for tooltip div element.

Comment (Veera81) [reply src/main/js/controls/Graph/Graph.js:399]: Can we move step removing the div element below the detachEventHadnlers function call? So we make sure that to make it the consistency with the removing other elements

Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Graph/Graph.js]: [fixed](https://github.com/cerner/carbon-graphs/pull/272/commits/6777bd4eee1600694c22412d3e110957caaadfb1#diff-4c7acbc816e711a56dc8fffdd18a4149R400)

File: src/test/unit/controls/Graph/GraphAxes-spec.js [hunk 3]
```diff
@@ -1997,4 +1997,21 @@ describe("Graph - Axes", () => {
...
+            });
+        });
+        describe("when graph is destroyed", () => {
+            it("remove div element for the popup tooltip", () => {
+                graph.destroy();
+                expect(
+                    fetchElementByClass(styles.labelPopupTooltip)
+                ).toBeNull();
+            });
+        });
```
Comment (sdadn) [inline src/test/unit/controls/Graph/GraphAxes-spec.js:2015]: Nit 1: These describe blocks seem redundant; you can simply combine the `describe` and `it` statements.
Nit 2, grammar: add -> adds, remove -> removes

File: src/test/unit/controls/Gantt/Track-spec.js [hunk 4]
```diff
@@ -735,4 +735,21 @@ describe("Gantt -> Track", () => {
...
+    describe("Gantt chart div element for the label popup tooltip ", () => {
+        describe("when chart is loaded", () => {
+            it("add div element for the popup tooltip", () => {
+                expect(
+                    fetchElementByClass(styles.labelPopupTooltip)
+                ).not.toBeNull();
+            });
+        });
+        describe("when chart is destroyed", () => {
+            it("remove div element for the popup tooltip", () => {
```
Comment (sdadn) [inline src/test/unit/controls/Gantt/Track-spec.js:747]: Grammar nit: add -> adds, remove -> removes

File: src/test/unit/controls/Graph/GraphAxes-spec.js (hunk 3 above)
Comment (Veera81) [reply src/test/unit/controls/Graph/GraphAxes-spec.js:2015]: nit: Probably, the upper describe block only looks redundant to me. You can remove that and keep the remaining `describe` and `it` blocks

you may use `should add` or `should remove` also

```js
        describe("when graph is loaded", () => {
            it("should add div element for the popup tooltip", () => {
                expect(
                    fetchElementByClass(styles.labelPopupTooltip)
                ).not.toBeNull();
            });
        });
        describe("when graph is destroyed", () => {
            it("should remove div element for the popup tooltip", () => {
                graph.destroy();
                expect(
                    fetchElementByClass(styles.labelPopupTooltip)
                ).toBeNull();
            });
        });
```

File: src/test/unit/controls/Gantt/Track-spec.js (hunk 4 above)
Comment (AshishMotanamGurunadham) [reply src/test/unit/controls/Gantt/Track-spec.js:747]: > Grammar nit: add -> adds, remove -> removes

[fixed](https://github.com/cerner/carbon-graphs/pull/272/commits/11a0be4eaf177602301435950dc6b3ff816881b0#diff-11aa0aaf6db553889f349765e88f7462R2000-R2012)

Comment (sdadn) [reply src/test/unit/controls/Gantt/Track-spec.js:747]: Nit: I think you missed this file.
add -> adds, remove -> removes

Comment (AshishMotanamGurunadham) [reply src/test/unit/controls/Gantt/Track-spec.js]: [fixed](https://github.com/cerner/carbon-graphs/pull/272/commits/91e81c529c41dadbf5a2a203614d91e9413226b0#diff-7fb4a16b40433875e7e73811189b4f84R738-R750)
