### PR TITLE
Fix: added new Bubble APIs (fixes #180)

### LINKED ISSUE #180: Accessibility: Color Contrast on Bubble Chart
Bubble Charts need a palette that meets accessibility guidelines of a contrast ratio of 3:1.

Currently, a range of colors are assigned to bubbles based on the user inputting two colors. This can lead to the steps from color A to color B being inaccessible. 

A color palette will need to be created to help insure that all colors meet WCAG accessibility guidelines. (Possibility of being able to hardcode a color palette instead of creating one based on a two color input?)

Screen Shot 2020-03-13 at 1 59 22 PM

### PR DESCRIPTION
**Pull request by sdadn**
**What is the purpose of this pull request? (Check any that's applicable)**

-   [ ] Feature
-   [x] Bug fix
-   [ ] Dependency updates
-   [ ] Documentation updates
-   [ ] Build related changes
-   [ ] Changes an existing functionality
-   [ ] Other, please explain:

**Does this introduce a breaking change?**

-   [ ] Yes
-   [x] No

**What changes did you make? (Give an overview)**
Addes 2 new APIs for Bubble charts that addresses accessibility issues
fixes #180 

**Add any screenshots**

Bubble Single Dataset API:
CleanShot 2020-10-06 at 09 18 37@2x

Bubble Multiple Dataset API:
CleanShot 2020-10-06 at 09 17 57@2x

### CODE REVIEW

**Comment by sdadn** [comment]
@jeremyfuksa can you look at:
http://localhost:9991/#/bubble/single-dataset-api 
http://localhost:9991/#/bubble/multiple-dataset-api

File: src/main/js/controls/Bubble/BubbleSingleDataset.js [hunk 1]
```diff
@@ -0,0 +1,200 @@
...
+     * @public
+     */
+    load(graph) {
+        if (graph.content.length > 1) {
+            console.warn("BubbleSingleDataset can only use one dataset.");
+            return this;
+        }
+
+        if (
+            utils.isUndefined(graph.content[0].config.color) &&
```
Comment (Veera81) [inline src/main/js/controls/Bubble/BubbleSingleDataset.js:52]: Why we are checking the color as undefined?

File: src/main/js/controls/Bubble/BubbleSingleDataset.js [hunk 2]
```diff
@@ -0,0 +1,200 @@
...
+ * @class BubbleSingleDataset
+ */
+class BubbleSingleDataset extends Bubble {
+    /**
+     * @inheritdoc
+     * @public
+     */
+    load(graph) {
+        if (graph.content.length > 1) {
+            console.warn("BubbleSingleDataset can only use one dataset.");
```
Comment (Veera81) [inline src/main/js/controls/Bubble/BubbleSingleDataset.js:47]: Is it worth having a warning? or Should we log an error if the consumer provides more than one dataset?

File: src/main/js/controls/Bubble/BubbleSingleDataset.js [hunk 3]
```diff
@@ -0,0 +1,200 @@
...
+            return this;
+        }
+
+        if (
+            utils.isUndefined(graph.content[0].config.color) &&
+            utils.isDefined(graph.content[0].config.palette) &&
+            graph.content[0].config.values.length >
+                BUBBLE.MAX_BUBBLES_SINGLE_DATASET
+        ) {
+            console.warn("Cannot plot more than 4 bubbles using shades.");
```
Comment (Veera81) [inline src/main/js/controls/Bubble/BubbleSingleDataset.js:57]: Is it worth having a warning? or Should we log an error if the consumer provides more than one dataset?

**Review by Veera81 — CHANGES_REQUESTED** [review]

File: dev/examples/controls/bubble.js [hunk 4]
```diff
@@ -387,3 +388,30 @@ export const renderBubbleGraphAndLegendPaddingReduced = (id) => {
     bubbleGraph.loadContent(Carbon.api.bubble(data6));
     return bubbleGraph;
 };
+
+export const renderBubbleSingleDataset = (id) => {
+    const bubbleGraph = Carbon.api.graph(axisData(`#${id}`));
+    data2.palette = BUBBLE.PALETTE.ORANGE;
+    data2.color = undefined;
```
[the remark this answers is not in the document]
Comment (sdadn) [reply dev/examples/controls/bubble.js:395]: because the example is to showcase the `palette` property and `color` overrides it.

File: src/main/js/helpers/constants.js [hunk 5]
```diff
@@ -53,6 +53,22 @@ export const COLORS = {
...
+
+export const BUBBLE = {
+    MAX_BUBBLES_SINGLE_DATASET: 4,
+    PALETTE: {
+        BLUE: ["#008fe0", "#044e7b", "#001624"],
+        GREEN: ["#4b9b1c", "#2c5e12", "#122702"],
+        ORANGE: ["#e46511", "#883e10", "#371a06"],
+        PINK: ["#ade868", "#6d0a48", "#32062a"],
+        PURPLE: ["#9c19a3", "#5c1060", "#240425"],
+        GRAY: "#949494"
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/constants.js:69]: Yes

File: src/main/js/controls/Bubble/BubbleMultipleDataset.js [hunk 6]
```diff
@@ -0,0 +1,157 @@
...
+        );
+        return this;
+    }
+
+    // /**
+    //  * @inheritdoc
+    //  */
+    // unload(graph) { ... }
+    //  inherited from class Bubble
+
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/controls/Bubble/BubbleMultipleDataset.js:84]: The purpose of this comment is to indicate that this lifecycle method is inherited from the parent class, but i can remove if unnecessary.

File: docs/controls/BubbleSingleDataset.md [hunk 7]
```diff
@@ -0,0 +1,327 @@
...
+    values: [
+        {
+            x: "2016-03-01T12:00:00Z",
+            y: 14,
+            weight: 15
+        },
+        {
+            x: "2016-04-10T12:00:00Z",
+            y: 1,
+            weight: 20
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleSingleDataset.md:167]: `hue` is being replaced by the new `palette` property.

File: docs/controls/BubbleMultipleDataset.md [hunk 8]
```diff
@@ -0,0 +1,273 @@
...
+For weight based bubble provide weight with `min` and `max`, each bubble can have a weight object in [Values](#values) level.
+
+```
+weight: {
+    min: 10,
+    max: 30,
+    maxRadius: 30
+}
+```
+
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md:230]: `hue` is no longer used in the new APIs.

File: src/main/js/controls/Bubble/BubbleSingleDataset.js (hunk 1 above)
Comment (sdadn) [reply src/main/js/controls/Bubble/BubbleSingleDataset.js:52]: `color` needs to be undefined in order to use `palette`

File: docs/controls/BubbleMultipleDataset.md [hunk 9]
```diff
@@ -0,0 +1,273 @@
...
+            -   [Required](#required-2)
+            -   [Optional](#optional-2)
+        -   [Regions](#regions)
+            -   [Required](#required-3)
+            -   [Optional](#optional-3)
+        -   [Constraints](#constraints)
+
+## Usage
+
+**Note: Bubble Muliple Dataset is limited to 7 datasets. any additional datasets will be ignored.**
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md:25]: We are limited to 7 distinct colors for each dataset. But this covers almost all use cases when we discussed it with UX.

File: dev/app.js [hunk 10]
```diff
@@ -497,6 +499,16 @@ renderSiteApp(
                     pathname: "/bubble/graph-and-legend-padding-reduced",
                     content: renderBubbleGraphAndLegendPaddingReduced,
                     title: "Graph and Legend Padding Reduced"
+                },
+                {
+                    pathname: "/bubble/single-dataset-api",
+                    content: renderBubbleSingleDataset,
```
Comment (AshishMotanamGurunadham) [inline dev/app.js:505]: I think it would be better if we rename it to **renderBubbleGraphWithSingleDataset**.

File: dev/app.js [hunk 11]
```diff
@@ -497,6 +499,16 @@ renderSiteApp(
...
+                    title: "Single Dataset API"
+                },
+                {
+                    pathname: "/bubble/multiple-dataset-api",
+                    content: renderBubbleMultipleDataset,
```
Comment (AshishMotanamGurunadham) [inline dev/app.js:510]: I think it would be better if we rename it to **renderBubbleGraphWithMultipleDataset**.

File: dev/app.js (hunk 10 above)
Comment (sdadn) [reply dev/app.js:505]: The name of the API is `BubbleSingleDataset`  so `renderBubbleGraphWithSingleDataset` seems to imply we're using the `Bubble` class. I can change it to `renderGraphBubbleSingleDataset` if that works.

File: src/main/js/controls/Bubble/BubbleSingleDataset.js (hunk 3 above)
Comment (sdadn) [reply src/main/js/controls/Bubble/BubbleSingleDataset.js:57]: The graph will be blank if there is more than 4 bubbles as agreed with UX. But any sort of feedback would be helpful for a consumer to know why the graph isn't rendering. I can update this to an error if that's more appropriate.

File: src/main/js/controls/Bubble/BubbleSingleDataset.js (hunk 2 above)
Comment (sdadn) [reply src/main/js/controls/Bubble/BubbleSingleDataset.js:47]: Yes, as any subsequent datasets will be ignored and the consumer needs to know why. I can update this to a warning if necessary.

**Comment by AshishMotanamGurunadham** [comment]
@sdadn Looks like datasets in others graphs are also going off when we datapoint. Is this expected behavior.

image

File: src/main/js/helpers/constants.js [hunk 12]
```diff
@@ -53,6 +53,22 @@ export const COLORS = {
     LAVENDER: "#8374c2",
     WHITE: "#ffffff"
 };
+/**
+ *
```
Comment (AshishMotanamGurunadham) [inline src/main/js/helpers/constants.js:57]: Can you please add small description on these color palettes.

File: docs/controls/BubbleMultipleDataset.md [hunk 13]
```diff
@@ -0,0 +1,274 @@
+# Bubble
```
Comment (AshishMotanamGurunadham) [inline docs/controls/BubbleMultipleDataset.md:1]: Can we change this to Bubble Multiple Dataset.

File: docs/controls/BubbleSingleDataset.md [hunk 14]
```diff
@@ -0,0 +1,327 @@
+# Bubble
```
Comment (AshishMotanamGurunadham) [inline docs/controls/BubbleSingleDataset.md:1]: Can we change name to Bubble Single Dataset

**Comment by sdadn** [comment]
> @sdadn Looks like datasets in others graphs are also going off when we datapoint. Is this expected behavior.
> 
> image

I was able to replicate this behavior using the original bubble class. If it's a bug, then it falls outside the scope of this issue. I believe it may be related to the Graph class.

**Review by AshishMotanamGurunadham — CHANGES_REQUESTED** [review]
> > @sdadn Looks like datasets in others graphs are also going off when we datapoint. Is this expected behavior.
> > image
> 
> I was able to replicate this behavior using the original bubble class. If it's a bug, then it falls outside the scope of this issue. I believe it may be related to the Graph class.

I guess things are working fine in Line graph.
image

File: docs/controls/BubbleMultipleDataset.md [hunk 15]
```diff
@@ -0,0 +1,274 @@
...
+| key           | string   | Unique id which represents the data-set |
+| values        | Array    | [Values](#values)                       |
+
+#### Optional
+
+| Property Name | Expected | Default      | Description                                                                               |
+| ------------- | -------- | ------------ | ----------------------------------------------------------------------------------------- |
+| color         | string   | COLORS.BLACK | Color for the bubbles                                                                     |
+| onClick       | Function | undefined    | Any action that can be performed when clicking on the data point                          |
+| hue           | object   | {}           | Provide lowerShade and upperShadefor color based bubble [Hue](#Hue)                       |
```
Comment (AshishMotanamGurunadham) [inline docs/controls/BubbleMultipleDataset.md:203]: Are we still using hue property?

File: docs/controls/BubbleMultipleDataset.md (hunk 13 above)
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md]: Updated here:
https://github.com/cerner/carbon-graphs/pull/308/commits/d5ccf1c09fb89321e361046b864e07099d3df278

File: docs/controls/BubbleSingleDataset.md (hunk 14 above)
Comment (sdadn) [reply docs/controls/BubbleSingleDataset.md]: Updated here:
https://github.com/cerner/carbon-graphs/pull/308/commits/d5ccf1c09fb89321e361046b864e07099d3df278

File: docs/controls/BubbleMultipleDataset.md [hunk 16]
```diff
@@ -0,0 +1,274 @@
...
+    min: 10,
+    max: 30,
+    maxRadius: 30
+}
+```
+
+#### Required
+
+| Property Name | Expected | Default   | Description                        |
+| ------------- | -------- | --------- | ---------------------------------- |
```
Comment (AshishMotanamGurunadham) [inline docs/controls/BubbleMultipleDataset.md:235]: Do we still need lower shade and upper shade properties?

File: docs/controls/BubbleSingleDataset.md [hunk 17]
```diff
@@ -0,0 +1,327 @@
...
+            y: 15
+        },
+        {
+            x: "2016-10-01T12:00:00Z",
+            y: 10
+        }
+    ]
+};
+var bubbleDefault = Carbon.api.graph(root);
+bubbleDefault.loadContent(Carbon.api.bubble(data));
```
Comment (AshishMotanamGurunadham) [inline docs/controls/BubbleSingleDataset.md:72]: Will we use Carbon.api.bubble in single data set?

File: docs/controls/BubbleSingleDataset.md [hunk 18]
```diff
@@ -0,0 +1,327 @@
...
+        }
+    ]
+};
+bubbleColorBased = Carbon.api.graph(root);
+bubbleColorBased.loadContent(Carbon.api.bubbleSingleDataset(colorBasedData));
+```
+
+#### Weight Color Based Bubble
+
+For a Weight and Color Based Bubble Graph, provide hue with lowerShade and upperShade, also provide weight with min and max also pass weight(thrid parameter)in the values as below content:
```
Comment (AshishMotanamGurunadham) [inline docs/controls/BubbleSingleDataset.md:145]: Are we still using hue?

File: dev/app.js (hunk 10 above)
Comment (sdadn) [reply dev/app.js]: fixed here:
https://github.com/cerner/carbon-graphs/pull/308/commits/100e84b9e54c438b8e2bf616e2ac7ea4fff6080b

File: dev/app.js (hunk 11 above)
Comment (sdadn) [reply dev/app.js]: fixed here:
https://github.com/cerner/carbon-graphs/pull/308/commits/100e84b9e54c438b8e2bf616e2ac7ea4fff6080b

File: src/main/js/controls/Bubble/BubbleMultipleDataset.js [hunk 19]
```diff
@@ -0,0 +1,157 @@
...
+class BubbleMultipleDataset extends Bubble {
+    /**
+     * @inheritdoc
+     * @public
+     */
+    load(graph) {
+        if (graph.content.length > 7) {
+            console.warn(
+                "BubbleSingleDataset is limited to a maximum of 7 datasets"
+            );
```
Comment (AshishMotanamGurunadham) [inline src/main/js/controls/Bubble/BubbleMultipleDataset.js:41]: Will execution stops if we give more than 7 datasets?

File: src/main/js/controls/Bubble/BubbleSingleDataset.js (hunk 3 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/controls/Bubble/BubbleSingleDataset.js:57]: Execution get stopped if we have more than 4 bubbles right?

File: src/main/js/controls/Bubble/BubbleMultipleDataset.js (hunk 19 above)
Comment (sdadn) [reply src/main/js/controls/Bubble/BubbleMultipleDataset.js:41]: No, it'll just ignore any datasets after 7 and won't load them.

File: src/main/js/controls/Bubble/helpers/colorGradient.js [hunk 20]
```diff
@@ -44,3 +44,52 @@ export const generateColor = (dataTarget) => {
...
+
+    if (utils.isUndefined(dataTarget.weight)) {
+        radiusData = dataTarget.values.map((element) => element.y);
+    } else {
+        radiusData = dataTarget.values.map((element) =>
+            bubbleScale(dataTarget)(element.weight)
+        );
+    }
+
+    let color = [];
```
Comment (AshishMotanamGurunadham) [inline src/main/js/controls/Bubble/helpers/colorGradient.js:66]: Can you please initialize everything at one place i mean at the start of method?

File: src/main/js/helpers/constants.js (hunk 12 above)
Comment (sdadn) [reply src/main/js/helpers/constants.js:57]: Added here:
https://github.com/cerner/carbon-graphs/pull/308/commits/a5a66a75beca5bc9ed5a4f706e9ea53dfa9a68e3

File: docs/controls/BubbleSingleDataset.md (hunk 17 above)
Comment (sdadn) [reply docs/controls/BubbleSingleDataset.md:72]: This was an accidental commit, i already fixed it. 
https://github.com/cerner/carbon-graphs/pull/308/commits/094103a7a84cee171af87eab44dd139833600078

File: src/main/js/controls/Bubble/helpers/colorGradient.js (hunk 20 above)
Comment (sdadn) [reply src/main/js/controls/Bubble/helpers/colorGradient.js]: Fixed here: 
https://github.com/cerner/carbon-graphs/pull/308/commits/c8a7c1526c25831c4090e4e4dcef279d75cc8fb7

**Comment by AshishMotanamGurunadham** [comment]
Did you tested all these changes in Internet Explorer?

File: src/test/unit/controls/Bubble/Bubble/BubbleLoad-spec.js [hunk 21]
```diff
@@ -40,6 +42,14 @@ describe("Bubble - Load", () => {
...
         document.body.innerHTML = "";
     });
+    beforeAll(() => {
+        // to supress warnings
+        consolewarn = console.warn;
+        console.warn = () => {};
+    });
+    afterAll(() => {
+        console.warn = consolewarn;
+    });
```
Comment (AshishMotanamGurunadham) [inline src/test/unit/controls/Bubble/Bubble/BubbleLoad-spec.js:52]: May i know what is purpose of these warn in before all and after all?

File: src/main/js/controls/Bubble/BubbleSingleDataset.js (hunk 3 above)
Comment (sdadn) [reply src/main/js/controls/Bubble/BubbleSingleDataset.js:57]: Yes, it won't render the data if there are more than 4 bubbles.

File: src/main/js/controls/Bubble/index.js [hunk 22]
```diff
@@ -1,3 +1,6 @@
 import Bubble from "./Bubble";
+import BubbleSingleDataset from "./BubbleSingleDataset";
+import BubbleMultipleDataset from "./BubbleMultipleDataset";
 
-export { Bubble as default };
+// export default {Bubble};
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/controls/Bubble/index.js]: removed:
https://github.com/cerner/carbon-graphs/pull/308/commits/94888f418603002244d9867a9688b86b7389d6f4

**Review by jeremyfuksa — CHANGES_REQUESTED** [review]
The single dataset example is not rendering in the browser.

File: dev/app.js [hunk 23]
```diff
@@ -497,6 +499,16 @@ renderSiteApp(
...
+                    title: "multiple Dataset API"
```
[the remark this answers is not in the document]
Comment (sdadn) [reply dev/app.js]: Fixed:
https://github.com/cerner/carbon-graphs/pull/308/commits/94888f418603002244d9867a9688b86b7389d6f4

**Comment by sdadn** [comment]
@jeremyfuksa It should be working now.

**Comment by sdadn** [comment]
@AshishMotanamGurunadham I have fixed the selection issue in https://github.com/cerner/carbon-graphs/pull/308/commits/0fd5c03ca49d10c05d143d89e3fb9f7829990ff7

File: docs/controls/BubbleMultipleDataset.md (hunk 16 above)
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md]: Removed: 
https://github.com/cerner/carbon-graphs/pull/308/commits/1a920bb9dc6643049ba404be1a3bcc8cd672e8ac

File: docs/controls/BubbleMultipleDataset.md (hunk 15 above)
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md]: Removed:
https://github.com/cerner/carbon-graphs/pull/308/commits/1a920bb9dc6643049ba404be1a3bcc8cd672e8ac

File: src/main/js/controls/Bubble/helpers/helpers.js [hunk 24]
```diff
@@ -513,16 +516,60 @@ const prepareLegendItems = (config, eventHandlers, dataTarget, legendSVG) => {
 const clear = (canvasSVG, dataTarget) =>
     d3RemoveElement(canvasSVG, `g[aria-describedby="${dataTarget.key}"]`);
 
+/**
+ * @typedef {object} Bubble
+ * @typedef {object} GraphContent
+ * @typedef {object} BubbleConfig
+ */
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/controls/Bubble/helpers/helpers.js]: Removed:
https://github.com/cerner/carbon-graphs/pull/308/commits/94888f418603002244d9867a9688b86b7389d6f4

File: docs/controls/BubbleSingleDataset.md (hunk 18 above)
Comment (sdadn) [reply docs/controls/BubbleSingleDataset.md]: fixed: 
https://github.com/cerner/carbon-graphs/pull/308/commits/1a920bb9dc6643049ba404be1a3bcc8cd672e8ac

**Review by Veera81 — APPROVED** [review]

File: src/test/unit/controls/Bubble/Bubble/BubbleLoad-spec.js (hunk 21 above)
Comment (sdadn) [reply src/test/unit/controls/Bubble/Bubble/BubbleLoad-spec.js:52]: This is so there are no warnings printed when running unit tests. The before block temporarily replaces the `console.warn` method and the after block restores it.

File: docs/controls/BubbleSingleDataset.md [hunk 25]
```diff
@@ -0,0 +1,327 @@
...
+        }
+    ]
+};
+bubbleWeightColorBased = Carbon.api.graph(root);
+bubbleWeightColorBased.loadContent(Carbon.api.bubbleSingleDataset(weightColorBasedData));
+```
+
+#### Custom Size Based Bubble
+
+For a custom size bubble, provide `maxRadius` in weight as given below between (min and max) and maxRadius maxRadius is given precedence.
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleSingleDataset.md]: Removed: 
https://github.com/cerner/carbon-graphs/pull/308/commits/7158471ea0ec47b81d885b06a02b4ac4da16dc33

**Comment by Veera81** [comment]
To fix the LGTM Error,

Remove the Unused import **BubbleConfig** from this file src/main/js/controls/Bubble/Bubble.js

image

File: src/main/js/controls/Bubble/BubbleSingleDataset.js (hunk 3 above)
Comment (mraplumb) [reply src/main/js/controls/Bubble/BubbleSingleDataset.js:57]: Given that the graph will not load when this happens, I think an error could be appropriate

File: src/main/js/controls/Bubble/BubbleSingleDataset.js [hunk 26]
```diff
@@ -0,0 +1,200 @@
...
+    //  */
+    // unload(graph) { ... }
+    //  inherited from class Bubble
+
+    /**
+     * @inheritdoc
+     */
+    resize(graph) {
+        if (utils.notEmpty(this.dataTarget.regions)) {
+            if (graph.content.length > 1 && !graph.config.shouldHideAllRegion) {
```
Comment (mraplumb) [inline src/main/js/controls/Bubble/BubbleSingleDataset.js:110]: would we ever fall into this true condition since a BubbleSingleDataset can only have one dataset?

File: src/main/js/controls/Bubble/helpers/colorGradient.js [hunk 27]
```diff
@@ -44,3 +44,52 @@ export const generateColor = (dataTarget) => {
...
+    if (utils.isUndefined(dataTarget.weight)) {
+        radiusData = dataTarget.values.map((element) => element.y);
+    } else {
+        radiusData = dataTarget.values.map((element) =>
+            bubbleScale(dataTarget)(element.weight)
+        );
+    }
+
+    if (utils.isDefined(dataTarget.palette)) {
+        color = dataTarget.palette;
```
Comment (mraplumb) [inline src/main/js/controls/Bubble/helpers/colorGradient.js:69]: I asked this above but what happens if a consumer provides a color palette that is invalid like `BUBBLE.PALETTE.OARNGE` instead of `BUBBLE.PALETTE.ORANGE`?

**Review by mraplumb — CHANGES_REQUESTED** [review]

**Comment by mraplumb** [comment]
Can we adjust the Multiple Data Set example so that the bubbles fall completely within the bounds of the graph?  There is one bubble that is slightly cut off at the top of the graph and another that is slightly cutoff at the bottom.

Also, can we remove the word "API" from the example names on the demo site?  We should probably also add a note in the existing bubble graph examples if they should be using one of the new methods instead.  If the other examples are still valid (i.e. Weight based), we should ensure they are using the new APIs.

File: docs/controls/BubbleMultipleDataset.md [hunk 28]
```diff
@@ -0,0 +1,266 @@
...
+
+**Note: Bubble Muliple Dataset is limited to 7 datasets. any additional datasets will be ignored.**
+
+### Structure
+
+You will **not** need all the properties in the example below.
+Check out _optional_/_required_ properties explained in the [JSON Properties](#json-properties) section.
+
+```javascript
+var root = {
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md:34]: I'm not sure. This is how it was in the original Bubble documentation. The other examples seem to use `var` as well.

File: docs/controls/BubbleMultipleDataset.md [hunk 29]
```diff
@@ -0,0 +1,266 @@
...
+| Property Name | Expected | Description                             |
+| ------------- | -------- | --------------------------------------- |
+| key           | string   | Unique id which represents the data-set |
+| values        | Array    | [Values](#values)                       |
+
+#### Optional
+
+| Property Name | Expected | Default      | Description                                                                               |
+| ------------- | -------- | ------------ | ----------------------------------------------------------------------------------------- |
+| color         | string   | COLORS.BLACK | Color for the bubbles                                                                     |
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md:201]: Any hex value can be used, as the colors are just hex constants. I believe this will be changed once we introduce theming.

File: src/main/js/helpers/constants.js [hunk 30]
```diff
@@ -53,6 +53,25 @@ export const COLORS = {
...
+export const BUBBLE = {
+    MAX_BUBBLES_SINGLE_DATASET: 4,
+    MAX_DATASETS_MULTIPLE_API: 7,
+    PALETTE: {
+        BLUE: ["#008fe0", "#044e7b", "#001624"],
+        GREEN: ["#4b9b1c", "#2c5e12", "#122702"],
+        ORANGE: ["#e46511", "#883e10", "#371a06"],
+        PINK: ["#ade868", "#6d0a48", "#32062a"],
+        PURPLE: ["#9c19a3", "#5c1060", "#240425"],
+        GRAY: "#949494"
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/helpers/constants.js:72]: These values have been provided by UX. The gray value is used in the situation where there are 4 bubbles, but not by itself.

File: src/main/js/controls/Bubble/BubbleMultipleDataset.js [hunk 31]
```diff
@@ -0,0 +1,157 @@
...
+ */
+class BubbleMultipleDataset extends Bubble {
+    /**
+     * @inheritdoc
+     * @public
+     */
+    load(graph) {
+        if (graph.content.length > BUBBLE.MAX_DATASETS_MULTIPLE_API) {
+            console.warn(
+                "BubbleSingleDataset is limited to a maximum of 7 datasets"
```
[the remark this answers is not in the document]
Comment (sdadn) [reply src/main/js/controls/Bubble/BubbleMultipleDataset.js]: Sorry, typo. Fixed here:
https://github.com/cerner/carbon-graphs/pull/308/commits/95321fb8737e69b5e1d2f30b2c57af25e4b7615c

File: docs/controls/BubbleMultipleDataset.md [hunk 32]
```diff
@@ -0,0 +1,266 @@
...
+        }
+    ]
+};
+var bubbleDefault = Carbon.api.graph(root);
+bubbleDefault.loadContent(Carbon.api.bubbleMultipleDataset(data));
+```
+
+#### Weight Based Bubble
+
+For weight based bubble Graph, provide weight with min and max and also pass weight as third paramter in the values and the weight(third parameter) should be in the range of min and max provide in the weight.
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md]: Looks like this is also an issue in the original bubble documentation. I have fixed them here.
https://github.com/cerner/carbon-graphs/pull/308/commits/0ed154dfd4fcf7b2fae1e1e34f9870fe67e30a83

File: docs/controls/BubbleSingleDataset.md [hunk 33]
```diff
@@ -0,0 +1,326 @@
...
+
+| Property Name | Expected | Default   | Description                              |
+| ------------- | -------- | --------- | ---------------------------------------- |
+| min           | number   | undefined | Min value for the weight based bubble    |
+| max           | number   | undefined | Max value for the weight based bubble    |
+| maxRadius     | number   | 30        | For custom size bubble provide maxRadius |
+
+### Palette
+
+For color based bubble provide a color constant for the shades. Only works if datapoints are <= 4 and if `color` is undefined
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleSingleDataset.md:274]: If `color` is provided, then `palette` will be ignored and there is no limit on data points.
If neither `color` nor `palette` are provided then the bubbles will be the default gray color:

CleanShot 2020-10-09 at 16 03 31@2x

File: src/main/js/controls/Bubble/helpers/colorGradient.js (hunk 27 above)
Comment (sdadn) [reply src/main/js/controls/Bubble/helpers/colorGradient.js:69]: In that case the bubbles will be rendered as gray.

File: docs/controls/BubbleMultipleDataset.md [hunk 34]
```diff
@@ -0,0 +1,266 @@
...
+        }
+    ]
+};
+var bubbleWeight = Carbon.api.graph(root);
+bubbleWeight.loadContent(Carbon.api.bubbleMultipleDataset(dataWeightBased));
+```
+
+#### Colored Bubbles
+
+For colored Bubbles, provide `color`:
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md]: Updated here:
https://github.com/cerner/carbon-graphs/pull/308/commits/9e415e0de172c8ff8bbc59f1e34225d95901b8b4

File: docs/controls/BubbleMultipleDataset.md [hunk 35]
```diff
@@ -0,0 +1,266 @@
...
+
+#### Optional
+
+| Property Name | Expected | Default | Description                                         |
+| ------------- | -------- | ------- | --------------------------------------------------- |
+| showElement   | boolean  | true    | Toggle to hide legend when legend item has no data. |
+
+### Weight
+
+For weight based bubble provide weight with `min` and `max`, each bubble can have a weight object in [Values](#values) level.
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md]: Fixed here:
https://github.com/cerner/carbon-graphs/pull/308/commits/ca406283282d085dcde51118bc54e7155b44bd18

File: docs/controls/BubbleMultipleDataset.md [hunk 36]
```diff
@@ -0,0 +1,266 @@
...
+#### Optional
+
+| Property Name | Expected | Default                                                            | Description                           |
+| ------------- | -------- | ------------------------------------------------------------------ | ------------------------------------- |
+| axis          | string   | "y"                                                                | Defines which axis if represents from |
+| color         | string   | ![#f4f4f4](https://placehold.it/15/f4f4f4/000000?text=+) `#f4f4f4` | Default color of the region area      |
+
+### Constraints
+
+-   If data-set `label` display is not provided then the legend item will not be shown as well
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md]: Correct. I reworded it to sound better:
https://github.com/cerner/carbon-graphs/pull/308/commits/ca406283282d085dcde51118bc54e7155b44bd18

File: docs/controls/BubbleMultipleDataset.md [hunk 37]
```diff
@@ -0,0 +1,273 @@
...
+
+### Weight
+
+For weight based bubble provide weight with `min` and `max`, each bubble can have a weight object in [Values](#values) level.
+
+```
+weight: {
+    min: 10,
+    max: 30,
+    maxRadius: 30
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md:232]: I think this section talks about the weight object and what properties are valid in it. I added some more detail to this section:
https://github.com/cerner/carbon-graphs/pull/308/commits/a6576ca8ccd4678058f2f594638a874c1cdf5334

File: docs/controls/BubbleSingleDataset.md [hunk 38]
```diff
@@ -0,0 +1,326 @@
...
+}
+```
+
+#### Optional
+
+| Property Name | Expected | Default   | Description                              |
+| ------------- | -------- | --------- | ---------------------------------------- |
+| min           | number   | undefined | Min value for the weight based bubble    |
+| max           | number   | undefined | Max value for the weight based bubble    |
+| maxRadius     | number   | 30        | For custom size bubble provide maxRadius |
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleSingleDataset.md]: Fixed here:
https://github.com/cerner/carbon-graphs/pull/308/commits/a6576ca8ccd4678058f2f594638a874c1cdf5334

File: docs/controls/BubbleMultipleDataset.md [hunk 39]
```diff
@@ -0,0 +1,273 @@
...
+        }
+    ]
+};
+bubbleColorBased = Carbon.api.graph(root);
+bubbleColorBased.loadContent(Carbon.api.bubbleMultipleDataset(colorBasedData));
+```
+
+#### Custom Size Based Bubble
+
+For a custom size bubble, provide `maxRadius` in weight as given below between (min and max) and maxRadius maxRadius is given precedence.
```
[the remark this answers is not in the document]
Comment (sdadn) [reply docs/controls/BubbleMultipleDataset.md]: I investigated the `maxRadius` property and it seems like `maxRadius` is applied to all bubbles in the dataset and overrides `min` and `max`. I rephrased this to be more understandable in the original bubble documentation and new APIs:
https://github.com/cerner/carbon-graphs/pull/308/commits/ed737dd45ddda24d1036ca327e1e03d13374337f

File: src/main/js/controls/Bubble/BubbleSingleDataset.js (hunk 26 above)
Comment (sdadn) [reply src/main/js/controls/Bubble/BubbleSingleDataset.js]: I tested it and seems like we don't. I removed this block here:
https://github.com/cerner/carbon-graphs/pull/308/commits/c3397298a95b82dd7a13c5bbe2e76e166cb29c83

**Review by AshishMotanamGurunadham — APPROVED** [review]

File: src/main/js/controls/Bubble/helpers/helpersMultipleDataset.js [hunk 40]
```diff
@@ -8,15 +8,12 @@ import constants from "../../../helpers/constants";
 import styles from "../../../helpers/styles";
 import utils from "../../../helpers/utils";
 import {
-    transformPoint,
+    areWeightsDefined,
     dataPointActionHandler,
     getDataPointValues,
-    decideRadius
```
Comment (mraplumb) [inline src/main/js/controls/Bubble/helpers/helpersMultipleDataset.js]: Why did we pull this out of the helpers file and duplicate it in two places?

Comment (sdadn) [reply src/main/js/controls/Bubble/helpers/helpersMultipleDataset.js]: Because this function had references for the `maxRadius` property. I left it as it is in the original helpers file so the original Bubble API is unchanged. The duplicated function has updated property name for the new APIs.

Comment (mraplumb) [reply src/main/js/controls/Bubble/helpers/helpersMultipleDataset.js]: I think that works for now but when we get to the point of deprecating the original Bubble graph in the next major release, it would be good to move this back into the common file and replace the existing one so that we only have one instance that both bubble APIs leverage.

**Review by mraplumb — APPROVED** [review]

**Comment by Veera81** [comment]
It's not related to bubble graphs and but to all graphs. It is the only issue in the IE

Attached recording issues for in the below zip file

[Issue.zip](https://github.com/cerner/carbon-graphs/files/5373735/Issue.zip)

**Review by jeremyfuksa — APPROVED** [review]
