### PR TITLE
Fix: Center Gantt chunks(fixes #31)

### LINKED ISSUE #31: Center Gantt chunks
Center align Gantt chunks (fixed width) on the time in which they are plotted. 
image

### PR DESCRIPTION
**Pull request by AshishMotanamGurunadham**
**What is the purpose of this pull request? (Check any that's applicable)**

-   [ ] Feature
-   [x] Bug fix
-   [ ] Dependency updates
-   [ ] Documentation updates
-   [ ] Build related changes
-   [ ] Changes an existing functionality
-   [ ] Other, please explain:

**Does this introduce a breaking change?**

-   [ ] Yes
-   [x] No

Dev site path example
- Please replace shape in action legend with diamond, rhombus, cross, vertical_bar, tear_alt, and tear_drop to see the changes
   https://engineering.cerner.com/carbon-graphs/#/line/simple

**What changes did you make? (Give an overview)**
- Centered all Gantt chart chunks which are not correctly aligned with the reference line.

**Add any screenshots**

**Before diamond:**
image

**After diamond:**
image

**Before triangle:**
image

**After triangle:**
image

**Before rhombus:**
image

**After rhombus:**
image

**Before cross:**
image

**After cross:**
image

**Before vertical_bar:**
image

**After vertical_bar:**
image

**Before tear_alt:**
image

**After tear_alt:**
image

**Before tear_drop:**
image

**After tear_drop:**
image

### CODE REVIEW

File: src/main/js/core/Shape/shapeDefinitions.js [hunk 1]
```diff
@@ -291,7 +291,7 @@ export const X_LIGHT = {
                 "M48 12L36 0 24 12 12 0 0 12l12 12L0 36l12 12 12-12 12 12 12-12-12-12 12-12zM36 43.8l-9.9-9.9-2.1-2.1-2.1 2.1-9.9 9.9L4.2 36l9.9-9.9 2.1-2.1-2.1-2.1L4.2 12 12 4.2l9.9 9.9 2.1 2.1 2.1-2.1L36 4.2l7.8 7.8-9.9 9.9-2.1 2.1 2.1 2.1 9.9 9.9-7.8 7.8z"
         }
     ],
-    options: { x: -6, y: -6, scale: 0.25 }
+    options: { x: -6.2, y: -6, scale: 0.25 }
```
Comment (Veera81) [inline src/main/js/core/Shape/shapeDefinitions.js:294]: What is this icon `X_LIGHT`?

File: src/main/js/core/Shape/shapeDefinitions.js [hunk 2]
```diff
@@ -271,7 +271,7 @@ export const TRIANGLE_DOWN_LIGHT = {
         { fill: "#FFF", d: "M42.7 7L24 38.2 5.3 7z" },
         { d: "M0 4l24 40L48 4H0zm42.7 3L24 38.2 5.3 7h37.4z" }
     ],
-    options: { x: -6, y: -6, scale: 0.25 }
+    options: { x: -6.2, y: -6, scale: 0.25 }
```
Comment (Veera81) [inline src/main/js/core/Shape/shapeDefinitions.js:274]: Why this triangle_down_light is little different than triangle_light? I mean why both have different values?

File: src/main/js/core/Shape/shapeDefinitions.js [hunk 3]
```diff
@@ -212,7 +212,7 @@ export const TEAR_DROP_LIGHT = {
                 "M38.4 17.6C28.7 5.9 23.9 0 23.9 0S19.1 5.9 9.5 17.5c-5.4 6.9-5.4 16.5 0 23.4 6.3 8 17.8 9.4 25.8 3.2.1 0 .1-.1.2-.2 8-6.5 9.3-18.2 2.9-26.3zM12 39.2c0-.1-.1-.1-.1-.2-4.6-5.8-4.6-13.9 0-19.7 5.7-6.8 9.7-11.7 12-14.5 2.3 2.8 6.4 7.8 12.2 14.7 5.4 6.8 4.3 16.6-2.4 22.1-6.7 5.3-16.3 4.3-21.7-2.4z"
         }
     ],
-    options: { x: -6, y: -6, scale: 0.25 }
+    options: { x: -6.2, y: -6, scale: 0.25 }
```
Comment (Veera81) [inline src/main/js/core/Shape/shapeDefinitions.js:215]: Did we verify all the shape definitions all are aligning center?

File: src/main/js/core/Shape/shapeDefinitions.js (hunk 1 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/core/Shape/shapeDefinitions.js:294]: we call light colored shape of X_LIGHT.
image

Here is the link for all light colors present in carbon https://engineering.cerner.com/carbon-graphs/#/styles/shapes/standard-light

File: src/main/js/core/Shape/shapeDefinitions.js (hunk 2 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/core/Shape/shapeDefinitions.js:274]: They no particular reason for why those are not same. I just tried to keep those shapes as perfect as i can. In that process i did adjusted in this way, so that they will look good on the reference line as well as dateline.

File: src/main/js/core/Shape/shapeDefinitions.js (hunk 3 above)
Comment (AshishMotanamGurunadham) [reply src/main/js/core/Shape/shapeDefinitions.js:215]: Other than the shapes i mentioned , we are only left with circle and square which is aligned perfectly onto the reference line.

**Review by Veera81 — APPROVED** [review]

**Review by jeremyfuksa — APPROVED** [review]

**Review by sdadn — APPROVED** [review]
